// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/benefit_event.proto

package benefitsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BenefitEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventId        string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	CycleId        string                 `protobuf:"bytes,3,opt,name=cycle_id,json=cycleId,proto3" json:"cycle_id,omitempty"`
	FeatureId      string                 `protobuf:"bytes,4,opt,name=feature_id,json=featureId,proto3" json:"feature_id,omitempty"`
	Category       string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Value          int64                  `protobuf:"varint,6,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp      int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BenefitEvent) Reset() {
	*x = BenefitEvent{}
	mi := &file_v1_benefit_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BenefitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BenefitEvent) ProtoMessage() {}

func (x *BenefitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_benefit_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BenefitEvent.ProtoReflect.Descriptor instead.
func (*BenefitEvent) Descriptor() ([]byte, []int) {
	return file_v1_benefit_event_proto_rawDescGZIP(), []int{0}
}

func (x *BenefitEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *BenefitEvent) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *BenefitEvent) GetCycleId() string {
	if x != nil {
		return x.CycleId
	}
	return ""
}

func (x *BenefitEvent) GetFeatureId() string {
	if x != nil {
		return x.FeatureId
	}
	return ""
}

func (x *BenefitEvent) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *BenefitEvent) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *BenefitEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_v1_benefit_event_proto protoreflect.FileDescriptor

const file_v1_benefit_event_proto_rawDesc = "" +
	"\n" +
	"\x16v1/benefit_event.proto\x12\n" +
	"benefitsv1\"\xdc\x01\n" +
	"\fBenefitEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tR\x0esubscriptionId\x12\x19\n" +
	"\bcycle_id\x18\x03 \x01(\tR\acycleId\x12\x1d\n" +
	"\n" +
	"feature_id\x18\x04 \x01(\tR\tfeatureId\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x14\n" +
	"\x05value\x18\x06 \x01(\x03R\x05value\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestampB<Z:gitlab.famapp.in/backend/flexprice/protos/pb/v1;benefitsv1b\x06proto3"

var (
	file_v1_benefit_event_proto_rawDescOnce sync.Once
	file_v1_benefit_event_proto_rawDescData []byte
)

func file_v1_benefit_event_proto_rawDescGZIP() []byte {
	file_v1_benefit_event_proto_rawDescOnce.Do(func() {
		file_v1_benefit_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_benefit_event_proto_rawDesc), len(file_v1_benefit_event_proto_rawDesc)))
	})
	return file_v1_benefit_event_proto_rawDescData
}

var file_v1_benefit_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_benefit_event_proto_goTypes = []any{
	(*BenefitEvent)(nil), // 0: benefitsv1.BenefitEvent
}
var file_v1_benefit_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_benefit_event_proto_init() }
func file_v1_benefit_event_proto_init() {
	if File_v1_benefit_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_benefit_event_proto_rawDesc), len(file_v1_benefit_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_benefit_event_proto_goTypes,
		DependencyIndexes: file_v1_benefit_event_proto_depIdxs,
		MessageInfos:      file_v1_benefit_event_proto_msgTypes,
	}.Build()
	File_v1_benefit_event_proto = out.File
	file_v1_benefit_event_proto_goTypes = nil
	file_v1_benefit_event_proto_depIdxs = nil
}
