// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: v1/benefit_event.proto

package benefitsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntryType int32

const (
	EntryType_ENTRY_TYPE_UNSPECIFIED EntryType = 0
	EntryType_GRANT                  EntryType = 1
	EntryType_REVERSAL               EntryType = 2
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "ENTRY_TYPE_UNSPECIFIED",
		1: "GRANT",
		2: "REVERSAL",
	}
	EntryType_value = map[string]int32{
		"ENTRY_TYPE_UNSPECIFIED": 0,
		"GRANT":                  1,
		"REVERSAL":               2,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_benefit_event_proto_enumTypes[0].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_v1_benefit_event_proto_enumTypes[0]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryType.Descriptor instead.
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return file_v1_benefit_event_proto_rawDescGZIP(), []int{0}
}

type BenefitEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventId         string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Username        string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	SubscriptionId  string                 `protobuf:"bytes,3,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	FeatureId       string                 `protobuf:"bytes,4,opt,name=feature_id,json=featureId,proto3" json:"feature_id,omitempty"`
	Category        string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Value           int64                  `protobuf:"varint,6,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp       int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BenefitType     string                 `protobuf:"bytes,8,opt,name=benefit_type,json=benefitType,proto3" json:"benefit_type,omitempty"`
	EntryType       EntryType              `protobuf:"varint,9,opt,name=entry_type,json=entryType,proto3,enum=benefitsv1.EntryType" json:"entry_type,omitempty"`
	OriginalEventId string                 `protobuf:"bytes,10,opt,name=original_event_id,json=originalEventId,proto3" json:"original_event_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BenefitEvent) Reset() {
	*x = BenefitEvent{}
	mi := &file_v1_benefit_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BenefitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BenefitEvent) ProtoMessage() {}

func (x *BenefitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_benefit_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BenefitEvent.ProtoReflect.Descriptor instead.
func (*BenefitEvent) Descriptor() ([]byte, []int) {
	return file_v1_benefit_event_proto_rawDescGZIP(), []int{0}
}

func (x *BenefitEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *BenefitEvent) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BenefitEvent) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *BenefitEvent) GetFeatureId() string {
	if x != nil {
		return x.FeatureId
	}
	return ""
}

func (x *BenefitEvent) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *BenefitEvent) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *BenefitEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BenefitEvent) GetBenefitType() string {
	if x != nil {
		return x.BenefitType
	}
	return ""
}

func (x *BenefitEvent) GetEntryType() EntryType {
	if x != nil {
		return x.EntryType
	}
	return EntryType_ENTRY_TYPE_UNSPECIFIED
}

func (x *BenefitEvent) GetOriginalEventId() string {
	if x != nil {
		return x.OriginalEventId
	}
	return ""
}

var File_v1_benefit_event_proto protoreflect.FileDescriptor

const file_v1_benefit_event_proto_rawDesc = "" +
	"\n" +
	"\x16v1/benefit_event.proto\x12\n" +
	"benefitsv1\"\xe2\x02\n" +
	"\fBenefitEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12'\n" +
	"\x0fsubscription_id\x18\x03 \x01(\tR\x0esubscriptionId\x12\x1d\n" +
	"\n" +
	"feature_id\x18\x04 \x01(\tR\tfeatureId\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x14\n" +
	"\x05value\x18\x06 \x01(\x03R\x05value\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12!\n" +
	"\fbenefit_type\x18\b \x01(\tR\vbenefitType\x124\n" +
	"\n" +
	"entry_type\x18\t \x01(\x0e2\x15.benefitsv1.EntryTypeR\tentryType\x12*\n" +
	"\x11original_event_id\x18\n" +
	" \x01(\tR\x0foriginalEventId*@\n" +
	"\tEntryType\x12\x1a\n" +
	"\x16ENTRY_TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05GRANT\x10\x01\x12\f\n" +
	"\bREVERSAL\x10\x02B<Z:gitlab.famapp.in/backend/flexprice/protos/pb/v1;benefitsv1b\x06proto3"

var (
	file_v1_benefit_event_proto_rawDescOnce sync.Once
	file_v1_benefit_event_proto_rawDescData []byte
)

func file_v1_benefit_event_proto_rawDescGZIP() []byte {
	file_v1_benefit_event_proto_rawDescOnce.Do(func() {
		file_v1_benefit_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_benefit_event_proto_rawDesc), len(file_v1_benefit_event_proto_rawDesc)))
	})
	return file_v1_benefit_event_proto_rawDescData
}

var file_v1_benefit_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_benefit_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_benefit_event_proto_goTypes = []any{
	(EntryType)(0),       // 0: benefitsv1.EntryType
	(*BenefitEvent)(nil), // 1: benefitsv1.BenefitEvent
}
var file_v1_benefit_event_proto_depIdxs = []int32{
	0, // 0: benefitsv1.BenefitEvent.entry_type:type_name -> benefitsv1.EntryType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_benefit_event_proto_init() }
func file_v1_benefit_event_proto_init() {
	if File_v1_benefit_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_benefit_event_proto_rawDesc), len(file_v1_benefit_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_benefit_event_proto_goTypes,
		DependencyIndexes: file_v1_benefit_event_proto_depIdxs,
		EnumInfos:         file_v1_benefit_event_proto_enumTypes,
		MessageInfos:      file_v1_benefit_event_proto_msgTypes,
	}.Build()
	File_v1_benefit_event_proto = out.File
	file_v1_benefit_event_proto_goTypes = nil
	file_v1_benefit_event_proto_depIdxs = nil
}
