syntax = "proto3";

package benefitsv1;

option go_package = "gitlab.famapp.in/backend/flexprice/protos/pb/v1;benefitsv1";


message BenefitEvent {
  string event_id        = 1;
  string username        = 2;
  string subscription_id = 3;
  string feature_id      = 4;
  string category        = 5;
  int64  value           = 6;
  int64  timestamp       = 7;
  string benefit_type    = 8; // lowercase: famcash, famcoins, flexcash;
}

message BenefitReversalEvent {
  string event_id          = 1;
  string username          = 2;
  int64  value             = 3;
  int64  timestamp         = 4;
  string original_event_id = 5;
}
