// Code generated by ent, DO NOT EDIT.

package benefitledger

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldTenantID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldUpdatedBy, v))
}

// EnvironmentID applies equality check predicate on the "environment_id" field. It's identical to EnvironmentIDEQ.
func EnvironmentID(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldEnvironmentID, v))
}

// EventID applies equality check predicate on the "event_id" field. It's identical to EventIDEQ.
func EventID(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldEventID, v))
}

// SubscriptionID applies equality check predicate on the "subscription_id" field. It's identical to SubscriptionIDEQ.
func SubscriptionID(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldSubscriptionID, v))
}

// CustomerID applies equality check predicate on the "customer_id" field. It's identical to CustomerIDEQ.
func CustomerID(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldCustomerID, v))
}

// Product applies equality check predicate on the "product" field. It's identical to ProductEQ.
func Product(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldProduct, v))
}

// CycleID applies equality check predicate on the "cycle_id" field. It's identical to CycleIDEQ.
func CycleID(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldCycleID, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldCategory, v))
}

// FeatureID applies equality check predicate on the "feature_id" field. It's identical to FeatureIDEQ.
func FeatureID(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldFeatureID, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v int) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldValue, v))
}

// EventTimestamp applies equality check predicate on the "event_timestamp" field. It's identical to EventTimestampEQ.
func EventTimestamp(v time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldEventTimestamp, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContainsFold(FieldTenantID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// EnvironmentIDEQ applies the EQ predicate on the "environment_id" field.
func EnvironmentIDEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldEnvironmentID, v))
}

// EnvironmentIDNEQ applies the NEQ predicate on the "environment_id" field.
func EnvironmentIDNEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNEQ(FieldEnvironmentID, v))
}

// EnvironmentIDIn applies the In predicate on the "environment_id" field.
func EnvironmentIDIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDNotIn applies the NotIn predicate on the "environment_id" field.
func EnvironmentIDNotIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNotIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDGT applies the GT predicate on the "environment_id" field.
func EnvironmentIDGT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGT(FieldEnvironmentID, v))
}

// EnvironmentIDGTE applies the GTE predicate on the "environment_id" field.
func EnvironmentIDGTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGTE(FieldEnvironmentID, v))
}

// EnvironmentIDLT applies the LT predicate on the "environment_id" field.
func EnvironmentIDLT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLT(FieldEnvironmentID, v))
}

// EnvironmentIDLTE applies the LTE predicate on the "environment_id" field.
func EnvironmentIDLTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLTE(FieldEnvironmentID, v))
}

// EnvironmentIDContains applies the Contains predicate on the "environment_id" field.
func EnvironmentIDContains(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContains(FieldEnvironmentID, v))
}

// EnvironmentIDHasPrefix applies the HasPrefix predicate on the "environment_id" field.
func EnvironmentIDHasPrefix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasPrefix(FieldEnvironmentID, v))
}

// EnvironmentIDHasSuffix applies the HasSuffix predicate on the "environment_id" field.
func EnvironmentIDHasSuffix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasSuffix(FieldEnvironmentID, v))
}

// EnvironmentIDIsNil applies the IsNil predicate on the "environment_id" field.
func EnvironmentIDIsNil() predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldIsNull(FieldEnvironmentID))
}

// EnvironmentIDNotNil applies the NotNil predicate on the "environment_id" field.
func EnvironmentIDNotNil() predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNotNull(FieldEnvironmentID))
}

// EnvironmentIDEqualFold applies the EqualFold predicate on the "environment_id" field.
func EnvironmentIDEqualFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEqualFold(FieldEnvironmentID, v))
}

// EnvironmentIDContainsFold applies the ContainsFold predicate on the "environment_id" field.
func EnvironmentIDContainsFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContainsFold(FieldEnvironmentID, v))
}

// EventIDEQ applies the EQ predicate on the "event_id" field.
func EventIDEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldEventID, v))
}

// EventIDNEQ applies the NEQ predicate on the "event_id" field.
func EventIDNEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNEQ(FieldEventID, v))
}

// EventIDIn applies the In predicate on the "event_id" field.
func EventIDIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldIn(FieldEventID, vs...))
}

// EventIDNotIn applies the NotIn predicate on the "event_id" field.
func EventIDNotIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNotIn(FieldEventID, vs...))
}

// EventIDGT applies the GT predicate on the "event_id" field.
func EventIDGT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGT(FieldEventID, v))
}

// EventIDGTE applies the GTE predicate on the "event_id" field.
func EventIDGTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGTE(FieldEventID, v))
}

// EventIDLT applies the LT predicate on the "event_id" field.
func EventIDLT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLT(FieldEventID, v))
}

// EventIDLTE applies the LTE predicate on the "event_id" field.
func EventIDLTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLTE(FieldEventID, v))
}

// EventIDContains applies the Contains predicate on the "event_id" field.
func EventIDContains(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContains(FieldEventID, v))
}

// EventIDHasPrefix applies the HasPrefix predicate on the "event_id" field.
func EventIDHasPrefix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasPrefix(FieldEventID, v))
}

// EventIDHasSuffix applies the HasSuffix predicate on the "event_id" field.
func EventIDHasSuffix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasSuffix(FieldEventID, v))
}

// EventIDEqualFold applies the EqualFold predicate on the "event_id" field.
func EventIDEqualFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEqualFold(FieldEventID, v))
}

// EventIDContainsFold applies the ContainsFold predicate on the "event_id" field.
func EventIDContainsFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContainsFold(FieldEventID, v))
}

// SubscriptionIDEQ applies the EQ predicate on the "subscription_id" field.
func SubscriptionIDEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldSubscriptionID, v))
}

// SubscriptionIDNEQ applies the NEQ predicate on the "subscription_id" field.
func SubscriptionIDNEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNEQ(FieldSubscriptionID, v))
}

// SubscriptionIDIn applies the In predicate on the "subscription_id" field.
func SubscriptionIDIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDNotIn applies the NotIn predicate on the "subscription_id" field.
func SubscriptionIDNotIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNotIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDGT applies the GT predicate on the "subscription_id" field.
func SubscriptionIDGT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGT(FieldSubscriptionID, v))
}

// SubscriptionIDGTE applies the GTE predicate on the "subscription_id" field.
func SubscriptionIDGTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGTE(FieldSubscriptionID, v))
}

// SubscriptionIDLT applies the LT predicate on the "subscription_id" field.
func SubscriptionIDLT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLT(FieldSubscriptionID, v))
}

// SubscriptionIDLTE applies the LTE predicate on the "subscription_id" field.
func SubscriptionIDLTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLTE(FieldSubscriptionID, v))
}

// SubscriptionIDContains applies the Contains predicate on the "subscription_id" field.
func SubscriptionIDContains(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContains(FieldSubscriptionID, v))
}

// SubscriptionIDHasPrefix applies the HasPrefix predicate on the "subscription_id" field.
func SubscriptionIDHasPrefix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasPrefix(FieldSubscriptionID, v))
}

// SubscriptionIDHasSuffix applies the HasSuffix predicate on the "subscription_id" field.
func SubscriptionIDHasSuffix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasSuffix(FieldSubscriptionID, v))
}

// SubscriptionIDEqualFold applies the EqualFold predicate on the "subscription_id" field.
func SubscriptionIDEqualFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEqualFold(FieldSubscriptionID, v))
}

// SubscriptionIDContainsFold applies the ContainsFold predicate on the "subscription_id" field.
func SubscriptionIDContainsFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContainsFold(FieldSubscriptionID, v))
}

// CustomerIDEQ applies the EQ predicate on the "customer_id" field.
func CustomerIDEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerIDNEQ applies the NEQ predicate on the "customer_id" field.
func CustomerIDNEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNEQ(FieldCustomerID, v))
}

// CustomerIDIn applies the In predicate on the "customer_id" field.
func CustomerIDIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldIn(FieldCustomerID, vs...))
}

// CustomerIDNotIn applies the NotIn predicate on the "customer_id" field.
func CustomerIDNotIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNotIn(FieldCustomerID, vs...))
}

// CustomerIDGT applies the GT predicate on the "customer_id" field.
func CustomerIDGT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGT(FieldCustomerID, v))
}

// CustomerIDGTE applies the GTE predicate on the "customer_id" field.
func CustomerIDGTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGTE(FieldCustomerID, v))
}

// CustomerIDLT applies the LT predicate on the "customer_id" field.
func CustomerIDLT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLT(FieldCustomerID, v))
}

// CustomerIDLTE applies the LTE predicate on the "customer_id" field.
func CustomerIDLTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLTE(FieldCustomerID, v))
}

// CustomerIDContains applies the Contains predicate on the "customer_id" field.
func CustomerIDContains(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContains(FieldCustomerID, v))
}

// CustomerIDHasPrefix applies the HasPrefix predicate on the "customer_id" field.
func CustomerIDHasPrefix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasPrefix(FieldCustomerID, v))
}

// CustomerIDHasSuffix applies the HasSuffix predicate on the "customer_id" field.
func CustomerIDHasSuffix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasSuffix(FieldCustomerID, v))
}

// CustomerIDEqualFold applies the EqualFold predicate on the "customer_id" field.
func CustomerIDEqualFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEqualFold(FieldCustomerID, v))
}

// CustomerIDContainsFold applies the ContainsFold predicate on the "customer_id" field.
func CustomerIDContainsFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContainsFold(FieldCustomerID, v))
}

// ProductEQ applies the EQ predicate on the "product" field.
func ProductEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldProduct, v))
}

// ProductNEQ applies the NEQ predicate on the "product" field.
func ProductNEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNEQ(FieldProduct, v))
}

// ProductIn applies the In predicate on the "product" field.
func ProductIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldIn(FieldProduct, vs...))
}

// ProductNotIn applies the NotIn predicate on the "product" field.
func ProductNotIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNotIn(FieldProduct, vs...))
}

// ProductGT applies the GT predicate on the "product" field.
func ProductGT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGT(FieldProduct, v))
}

// ProductGTE applies the GTE predicate on the "product" field.
func ProductGTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGTE(FieldProduct, v))
}

// ProductLT applies the LT predicate on the "product" field.
func ProductLT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLT(FieldProduct, v))
}

// ProductLTE applies the LTE predicate on the "product" field.
func ProductLTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLTE(FieldProduct, v))
}

// ProductContains applies the Contains predicate on the "product" field.
func ProductContains(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContains(FieldProduct, v))
}

// ProductHasPrefix applies the HasPrefix predicate on the "product" field.
func ProductHasPrefix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasPrefix(FieldProduct, v))
}

// ProductHasSuffix applies the HasSuffix predicate on the "product" field.
func ProductHasSuffix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasSuffix(FieldProduct, v))
}

// ProductEqualFold applies the EqualFold predicate on the "product" field.
func ProductEqualFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEqualFold(FieldProduct, v))
}

// ProductContainsFold applies the ContainsFold predicate on the "product" field.
func ProductContainsFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContainsFold(FieldProduct, v))
}

// CycleIDEQ applies the EQ predicate on the "cycle_id" field.
func CycleIDEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldCycleID, v))
}

// CycleIDNEQ applies the NEQ predicate on the "cycle_id" field.
func CycleIDNEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNEQ(FieldCycleID, v))
}

// CycleIDIn applies the In predicate on the "cycle_id" field.
func CycleIDIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldIn(FieldCycleID, vs...))
}

// CycleIDNotIn applies the NotIn predicate on the "cycle_id" field.
func CycleIDNotIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNotIn(FieldCycleID, vs...))
}

// CycleIDGT applies the GT predicate on the "cycle_id" field.
func CycleIDGT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGT(FieldCycleID, v))
}

// CycleIDGTE applies the GTE predicate on the "cycle_id" field.
func CycleIDGTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGTE(FieldCycleID, v))
}

// CycleIDLT applies the LT predicate on the "cycle_id" field.
func CycleIDLT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLT(FieldCycleID, v))
}

// CycleIDLTE applies the LTE predicate on the "cycle_id" field.
func CycleIDLTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLTE(FieldCycleID, v))
}

// CycleIDContains applies the Contains predicate on the "cycle_id" field.
func CycleIDContains(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContains(FieldCycleID, v))
}

// CycleIDHasPrefix applies the HasPrefix predicate on the "cycle_id" field.
func CycleIDHasPrefix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasPrefix(FieldCycleID, v))
}

// CycleIDHasSuffix applies the HasSuffix predicate on the "cycle_id" field.
func CycleIDHasSuffix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasSuffix(FieldCycleID, v))
}

// CycleIDEqualFold applies the EqualFold predicate on the "cycle_id" field.
func CycleIDEqualFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEqualFold(FieldCycleID, v))
}

// CycleIDContainsFold applies the ContainsFold predicate on the "cycle_id" field.
func CycleIDContainsFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContainsFold(FieldCycleID, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContainsFold(FieldCategory, v))
}

// FeatureIDEQ applies the EQ predicate on the "feature_id" field.
func FeatureIDEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldFeatureID, v))
}

// FeatureIDNEQ applies the NEQ predicate on the "feature_id" field.
func FeatureIDNEQ(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNEQ(FieldFeatureID, v))
}

// FeatureIDIn applies the In predicate on the "feature_id" field.
func FeatureIDIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldIn(FieldFeatureID, vs...))
}

// FeatureIDNotIn applies the NotIn predicate on the "feature_id" field.
func FeatureIDNotIn(vs ...string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNotIn(FieldFeatureID, vs...))
}

// FeatureIDGT applies the GT predicate on the "feature_id" field.
func FeatureIDGT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGT(FieldFeatureID, v))
}

// FeatureIDGTE applies the GTE predicate on the "feature_id" field.
func FeatureIDGTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGTE(FieldFeatureID, v))
}

// FeatureIDLT applies the LT predicate on the "feature_id" field.
func FeatureIDLT(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLT(FieldFeatureID, v))
}

// FeatureIDLTE applies the LTE predicate on the "feature_id" field.
func FeatureIDLTE(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLTE(FieldFeatureID, v))
}

// FeatureIDContains applies the Contains predicate on the "feature_id" field.
func FeatureIDContains(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContains(FieldFeatureID, v))
}

// FeatureIDHasPrefix applies the HasPrefix predicate on the "feature_id" field.
func FeatureIDHasPrefix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasPrefix(FieldFeatureID, v))
}

// FeatureIDHasSuffix applies the HasSuffix predicate on the "feature_id" field.
func FeatureIDHasSuffix(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldHasSuffix(FieldFeatureID, v))
}

// FeatureIDIsNil applies the IsNil predicate on the "feature_id" field.
func FeatureIDIsNil() predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldIsNull(FieldFeatureID))
}

// FeatureIDNotNil applies the NotNil predicate on the "feature_id" field.
func FeatureIDNotNil() predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNotNull(FieldFeatureID))
}

// FeatureIDEqualFold applies the EqualFold predicate on the "feature_id" field.
func FeatureIDEqualFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEqualFold(FieldFeatureID, v))
}

// FeatureIDContainsFold applies the ContainsFold predicate on the "feature_id" field.
func FeatureIDContainsFold(v string) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldContainsFold(FieldFeatureID, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v int) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v int) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...int) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...int) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v int) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v int) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v int) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v int) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLTE(FieldValue, v))
}

// EventTimestampEQ applies the EQ predicate on the "event_timestamp" field.
func EventTimestampEQ(v time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldEQ(FieldEventTimestamp, v))
}

// EventTimestampNEQ applies the NEQ predicate on the "event_timestamp" field.
func EventTimestampNEQ(v time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNEQ(FieldEventTimestamp, v))
}

// EventTimestampIn applies the In predicate on the "event_timestamp" field.
func EventTimestampIn(vs ...time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldIn(FieldEventTimestamp, vs...))
}

// EventTimestampNotIn applies the NotIn predicate on the "event_timestamp" field.
func EventTimestampNotIn(vs ...time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldNotIn(FieldEventTimestamp, vs...))
}

// EventTimestampGT applies the GT predicate on the "event_timestamp" field.
func EventTimestampGT(v time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGT(FieldEventTimestamp, v))
}

// EventTimestampGTE applies the GTE predicate on the "event_timestamp" field.
func EventTimestampGTE(v time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldGTE(FieldEventTimestamp, v))
}

// EventTimestampLT applies the LT predicate on the "event_timestamp" field.
func EventTimestampLT(v time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLT(FieldEventTimestamp, v))
}

// EventTimestampLTE applies the LTE predicate on the "event_timestamp" field.
func EventTimestampLTE(v time.Time) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.FieldLTE(FieldEventTimestamp, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BenefitLedger) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BenefitLedger) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BenefitLedger) predicate.BenefitLedger {
	return predicate.BenefitLedger(sql.NotPredicates(p))
}
