-- Create "addon_associations" table
CREATE TABLE "addon_associations" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "entity_id" character varying(50) NOT NULL,
  "entity_type" character varying(50) NOT NULL,
  "addon_id" character varying(50) NOT NULL,
  "start_date" timestamptz NULL,
  "end_date" timestamptz NULL,
  "addon_status" character varying(20) NOT NULL DEFAULT 'active',
  "cancellation_reason" character varying(255) NULL,
  "cancelled_at" timestamptz NULL,
  "metadata" jsonb NULL,
  PRIMARY KEY ("id")
);
-- Create index "addonassociation_tenant_id_environment_id_entity_id_entity_type" to table: "addon_associations"
CREATE INDEX "addonassociation_tenant_id_environment_id_entity_id_entity_type" ON "addon_associations" ("tenant_id", "environment_id", "entity_id", "entity_type", "addon_id");
-- Create "alert_logs" table
CREATE TABLE "alert_logs" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "entity_type" character varying(50) NOT NULL,
  "entity_id" character varying(50) NOT NULL,
  "parent_entity_type" character varying(50) NULL,
  "parent_entity_id" character varying(50) NULL,
  "customer_id" character varying(50) NULL,
  "alert_type" character varying(50) NOT NULL,
  "alert_status" character varying(50) NOT NULL,
  "alert_info" jsonb NOT NULL,
  "alert_setting_id" character varying(50) NULL,
  PRIMARY KEY ("id")
);
-- Create index "idx_alertlogs_alert_setting_id" to table: "alert_logs"
CREATE INDEX "idx_alertlogs_alert_setting_id" ON "alert_logs" ("tenant_id", "environment_id", "alert_setting_id", "created_at");
-- Create index "idx_alertlogs_customer_type_status_created_at" to table: "alert_logs"
CREATE INDEX "idx_alertlogs_customer_type_status_created_at" ON "alert_logs" ("tenant_id", "environment_id", "customer_id", "alert_type", "alert_status", "created_at");
-- Create index "idx_alertlogs_entity" to table: "alert_logs"
CREATE INDEX "idx_alertlogs_entity" ON "alert_logs" ("tenant_id", "environment_id", "entity_type", "entity_id");
-- Create index "idx_alertlogs_entity_created_at" to table: "alert_logs"
CREATE INDEX "idx_alertlogs_entity_created_at" ON "alert_logs" ("tenant_id", "environment_id", "entity_type", "entity_id", "created_at");
-- Create index "idx_alertlogs_entity_parent_created_at" to table: "alert_logs"
CREATE INDEX "idx_alertlogs_entity_parent_created_at" ON "alert_logs" ("tenant_id", "environment_id", "entity_type", "entity_id", "parent_entity_type", "parent_entity_id", "created_at");
-- Create index "idx_alertlogs_type" to table: "alert_logs"
CREATE INDEX "idx_alertlogs_type" ON "alert_logs" ("tenant_id", "environment_id", "alert_type");
-- Create "alert_settings" table
CREATE TABLE "alert_settings" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "enabled" boolean NOT NULL DEFAULT true,
  "entity_type" character varying NOT NULL,
  "entity_id" character varying(50) NOT NULL,
  "parent_entity_type" character varying NULL,
  "parent_entity_id" character varying(50) NULL,
  "config" jsonb NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "idx_alert_settings_entity" to table: "alert_settings"
CREATE INDEX "idx_alert_settings_entity" ON "alert_settings" ("tenant_id", "environment_id", "status", "enabled", "entity_type", "entity_id");
-- Create index "idx_alert_settings_parent" to table: "alert_settings"
CREATE INDEX "idx_alert_settings_parent" ON "alert_settings" ("tenant_id", "environment_id", "status", "enabled", "entity_type", "parent_entity_type", "parent_entity_id");
-- Create "auths" table
CREATE TABLE "auths" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" character varying(50) NOT NULL,
  "provider" character varying(20) NOT NULL,
  "token" text NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "idx_auth_created_at" to table: "auths"
CREATE INDEX "idx_auth_created_at" ON "auths" ("created_at");
-- Create index "idx_auth_provider" to table: "auths"
CREATE INDEX "idx_auth_provider" ON "auths" ("provider");
-- Create index "idx_auth_status" to table: "auths"
CREATE INDEX "idx_auth_status" ON "auths" ("status");
-- Create index "idx_auth_user_id_unique" to table: "auths"
CREATE UNIQUE INDEX "idx_auth_user_id_unique" ON "auths" ("user_id") WHERE ((status)::text = 'published'::text);
-- Create "billing_sequences" table
CREATE TABLE "billing_sequences" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" character varying(50) NOT NULL,
  "subscription_id" character varying(50) NOT NULL,
  "last_sequence" integer NOT NULL DEFAULT 0,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "billingsequence_tenant_id_subscription_id" to table: "billing_sequences"
CREATE UNIQUE INDEX "billingsequence_tenant_id_subscription_id" ON "billing_sequences" ("tenant_id", "subscription_id");
-- Create "checkout_sessions" table
CREATE TABLE "checkout_sessions" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "customer_id" character varying(50) NOT NULL,
  "action" character varying(30) NOT NULL,
  "checkout_status" character varying(20) NOT NULL DEFAULT 'initiated',
  "payment_provider" character varying(20) NOT NULL,
  "checkout_invoice_id" character varying(50) NULL,
  "checkout_payment_id" character varying(50) NULL,
  "configuration" jsonb NOT NULL,
  "payment_provider_config" jsonb NULL,
  "result" jsonb NULL,
  "provider_result" jsonb NULL,
  "idempotency_key" character varying(255) NULL,
  "success_url" text NULL,
  "failure_url" text NULL,
  "cancel_url" text NULL,
  "expires_at" timestamptz NULL,
  "completed_at" timestamptz NULL,
  "cancelled_at" timestamptz NULL,
  "failure_reason" text NULL,
  "metadata" jsonb NULL,
  PRIMARY KEY ("id")
);
-- Create index "idx_checkout_session_customer" to table: "checkout_sessions"
CREATE INDEX "idx_checkout_session_customer" ON "checkout_sessions" ("tenant_id", "environment_id", "customer_id");
-- Create index "idx_checkout_session_expiry" to table: "checkout_sessions"
CREATE INDEX "idx_checkout_session_expiry" ON "checkout_sessions" ("expires_at") WHERE ((checkout_status)::text = ANY ((ARRAY['initiated'::character varying, 'pending'::character varying])::text[]));
-- Create index "idx_checkout_session_idempotency_key_active" to table: "checkout_sessions"
CREATE UNIQUE INDEX "idx_checkout_session_idempotency_key_active" ON "checkout_sessions" ("tenant_id", "environment_id", "idempotency_key") WHERE ((idempotency_key IS NOT NULL) AND ((checkout_status)::text = ANY ((ARRAY['initiated'::character varying, 'pending'::character varying])::text[])));
-- Create "connections" table
CREATE TABLE "connections" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "name" character varying(255) NOT NULL,
  "provider_type" character varying(50) NOT NULL,
  "encrypted_secret_data" jsonb NULL,
  "metadata" jsonb NULL,
  "sync_config" jsonb NULL,
  PRIMARY KEY ("id")
);
-- Create index "connection_tenant_id_environment_id_provider_type" to table: "connections"
CREATE INDEX "connection_tenant_id_environment_id_provider_type" ON "connections" ("tenant_id", "environment_id", "provider_type");
-- Create "credit_grant_applications" table
CREATE TABLE "credit_grant_applications" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "credit_grant_id" character varying(50) NOT NULL,
  "subscription_id" character varying(50) NOT NULL,
  "scheduled_for" timestamptz NOT NULL,
  "applied_at" timestamptz NULL,
  "period_start" timestamptz NOT NULL,
  "period_end" timestamptz NULL,
  "application_status" character varying NOT NULL DEFAULT 'pending',
  "credits" numeric(20,8) NOT NULL,
  "application_reason" text NOT NULL,
  "subscription_status_at_application" character varying(50) NOT NULL,
  "retry_count" bigint NOT NULL DEFAULT 0,
  "failure_reason" text NULL,
  "metadata" jsonb NULL,
  "idempotency_key" character varying(100) NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "credit_grant_applications_idempotency_key_key" to table: "credit_grant_applications"
CREATE UNIQUE INDEX "credit_grant_applications_idempotency_key_key" ON "credit_grant_applications" ("idempotency_key");
-- Create "entity_integration_mappings" table
CREATE TABLE "entity_integration_mappings" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "entity_id" character varying(255) NOT NULL,
  "entity_type" character varying(50) NOT NULL,
  "provider_type" character varying(50) NOT NULL,
  "provider_entity_id" character varying(255) NOT NULL,
  "metadata" jsonb NULL,
  PRIMARY KEY ("id")
);
-- Create index "entityintegrationmapping_provider_type_provider_entity_id" to table: "entity_integration_mappings"
CREATE INDEX "entityintegrationmapping_provider_type_provider_entity_id" ON "entity_integration_mappings" ("provider_type", "provider_entity_id");
-- Create index "idx_entity_integration_mapping_unique" to table: "entity_integration_mappings"
CREATE UNIQUE INDEX "idx_entity_integration_mapping_unique" ON "entity_integration_mappings" ("tenant_id", "environment_id", "entity_type", "entity_id", "provider_type") WHERE ((status)::text = 'published'::text);
-- Create "environments" table
CREATE TABLE "environments" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "name" character varying(50) NOT NULL,
  "type" character varying(20) NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "idx_environment_tenant_created_at" to table: "environments"
CREATE INDEX "idx_environment_tenant_created_at" ON "environments" ("tenant_id", "created_at");
-- Create index "idx_environment_tenant_id_type" to table: "environments"
CREATE INDEX "idx_environment_tenant_id_type" ON "environments" ("tenant_id", "type");
-- Create index "idx_environment_tenant_status" to table: "environments"
CREATE INDEX "idx_environment_tenant_status" ON "environments" ("tenant_id", "status");
-- Create "features" table
CREATE TABLE "features" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "lookup_key" character varying(255) NOT NULL,
  "name" character varying(255) NOT NULL,
  "description" text NULL,
  "type" character varying(50) NOT NULL,
  "meter_id" character varying(50) NULL,
  "metadata" jsonb NULL,
  "unit_singular" character varying(50) NULL,
  "unit_plural" character varying(50) NULL,
  "reporting_unit_singular" character varying(255) NULL,
  "reporting_unit_plural" character varying(255) NULL,
  "reporting_unit_conversion_rate" numeric(20,10) NULL,
  "alert_settings" jsonb NULL,
  "group_id" character varying(50) NULL,
  PRIMARY KEY ("id")
);
-- Create index "idx_feature_tenant_env_created_at" to table: "features"
CREATE INDEX "idx_feature_tenant_env_created_at" ON "features" ("tenant_id", "environment_id", "created_at");
-- Create index "idx_feature_tenant_env_group_id" to table: "features"
CREATE INDEX "idx_feature_tenant_env_group_id" ON "features" ("tenant_id", "environment_id", "group_id");
-- Create index "idx_feature_tenant_env_lookup_key_unique" to table: "features"
CREATE UNIQUE INDEX "idx_feature_tenant_env_lookup_key_unique" ON "features" ("tenant_id", "environment_id", "lookup_key") WHERE ((lookup_key IS NOT NULL) AND ((lookup_key)::text <> ''::text) AND ((status)::text = 'published'::text));
-- Create index "idx_feature_tenant_env_meter_id" to table: "features"
CREATE INDEX "idx_feature_tenant_env_meter_id" ON "features" ("tenant_id", "environment_id", "meter_id") WHERE (meter_id IS NOT NULL);
-- Create index "idx_feature_tenant_env_status" to table: "features"
CREATE INDEX "idx_feature_tenant_env_status" ON "features" ("tenant_id", "environment_id", "status");
-- Create index "idx_feature_tenant_env_type" to table: "features"
CREATE INDEX "idx_feature_tenant_env_type" ON "features" ("tenant_id", "environment_id", "type");
-- Create "groups" table
CREATE TABLE "groups" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "metadata" jsonb NULL,
  "name" character varying(255) NOT NULL,
  "entity_type" character varying(50) NOT NULL DEFAULT 'price',
  "lookup_key" character varying(255) NULL,
  PRIMARY KEY ("id")
);
-- Create index "group_tenant_id_environment_id" to table: "groups"
CREATE INDEX "group_tenant_id_environment_id" ON "groups" ("tenant_id", "environment_id");
-- Create index "idx_group_tenant_environment_lookup_key" to table: "groups"
CREATE UNIQUE INDEX "idx_group_tenant_environment_lookup_key" ON "groups" ("tenant_id", "environment_id", "lookup_key") WHERE (((status)::text = 'published'::text) AND (lookup_key IS NOT NULL) AND ((lookup_key)::text <> ''::text));
-- Create "incoming_webhook_events" table
CREATE TABLE "incoming_webhook_events" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "provider" character varying(50) NOT NULL,
  "method" character varying(10) NOT NULL,
  "path" text NOT NULL,
  "request_id" character varying(100) NULL,
  "headers" jsonb NULL,
  "body" text NULL,
  PRIMARY KEY ("id")
);
-- Create index "idx_incoming_webhook_events_request_id" to table: "incoming_webhook_events"
CREATE INDEX "idx_incoming_webhook_events_request_id" ON "incoming_webhook_events" ("request_id");
-- Create index "idx_incoming_webhook_events_tenant_env_created" to table: "incoming_webhook_events"
CREATE INDEX "idx_incoming_webhook_events_tenant_env_created" ON "incoming_webhook_events" ("tenant_id", "environment_id", "created_at");
-- Create index "idx_incoming_webhook_events_tenant_env_provider_created" to table: "incoming_webhook_events"
CREATE INDEX "idx_incoming_webhook_events_tenant_env_provider_created" ON "incoming_webhook_events" ("tenant_id", "environment_id", "provider", "created_at");
-- Create "invoice_sequences" table
CREATE TABLE "invoice_sequences" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" character varying(50) NOT NULL,
  "environment_id" character varying(50) NULL,
  "year_month" character varying(6) NOT NULL,
  "last_value" bigint NOT NULL DEFAULT 0,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "invoicesequence_tenant_id_environment_id_year_month" to table: "invoice_sequences"
CREATE UNIQUE INDEX "invoicesequence_tenant_id_environment_id_year_month" ON "invoice_sequences" ("tenant_id", "environment_id", "year_month");
-- Create "meters" table
CREATE TABLE "meters" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "event_name" character varying(255) NOT NULL,
  "name" character varying(255) NOT NULL,
  "aggregation" jsonb NOT NULL,
  "filters" jsonb NOT NULL,
  "reset_usage" character varying(20) NOT NULL DEFAULT 'BILLING_PERIOD',
  PRIMARY KEY ("id")
);
-- Create index "meter_tenant_id_environment_id" to table: "meters"
CREATE INDEX "meter_tenant_id_environment_id" ON "meters" ("tenant_id", "environment_id");
-- Create "payment_methods" table
CREATE TABLE "payment_methods" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "customer_id" character varying(50) NOT NULL,
  "type" character varying(50) NOT NULL,
  "gateway" character varying(50) NOT NULL,
  "gateway_method_id" character varying(255) NOT NULL,
  "payment_method_status" character varying(50) NOT NULL DEFAULT 'ACTIVE',
  "is_default" boolean NOT NULL DEFAULT false,
  "method_details" jsonb NULL,
  PRIMARY KEY ("id")
);
-- Create index "paymentmethod_tenant_id_environment_id_customer_id_status" to table: "payment_methods"
CREATE INDEX "paymentmethod_tenant_id_environment_id_customer_id_status" ON "payment_methods" ("tenant_id", "environment_id", "customer_id", "status") WHERE ((status)::text = 'published'::text);
-- Create "price_units" table
CREATE TABLE "price_units" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "metadata" jsonb NULL,
  "name" character varying(255) NOT NULL,
  "code" character varying(3) NOT NULL,
  "symbol" character varying(10) NOT NULL,
  "base_currency" character varying(3) NOT NULL,
  "conversion_rate" numeric(10,5) NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "priceunit_tenant_id_environment_id_code" to table: "price_units"
CREATE UNIQUE INDEX "priceunit_tenant_id_environment_id_code" ON "price_units" ("tenant_id", "environment_id", "code") WHERE ((status)::text = 'published'::text);
-- Create "refunds" table
CREATE TABLE "refunds" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "payment_id" character varying(50) NOT NULL,
  "payment_gateway" character varying(50) NOT NULL,
  "gateway_refund_id" character varying(255) NULL,
  "gateway_tracking_id" character varying(255) NULL,
  "amount" numeric(20,8) NOT NULL,
  "currency" character varying(10) NOT NULL,
  "refund_status" character varying(50) NOT NULL,
  "refund_reason" character varying(50) NOT NULL,
  "idempotency_key" character varying(255) NOT NULL,
  "gateway_idempotency_token" character varying(255) NOT NULL,
  "failure_reason" text NULL,
  "metadata" jsonb NULL,
  "gateway_metadata" jsonb NULL,
  "initiated_at" timestamptz NULL,
  "succeeded_at" timestamptz NULL,
  "failed_at" timestamptz NULL,
  "cancelled_at" timestamptz NULL,
  PRIMARY KEY ("id")
);
-- Create index "idx_refund_gateway_refund_id" to table: "refunds"
CREATE INDEX "idx_refund_gateway_refund_id" ON "refunds" ("gateway_refund_id");
-- Create index "idx_refund_tenant_env_idempotency" to table: "refunds"
CREATE UNIQUE INDEX "idx_refund_tenant_env_idempotency" ON "refunds" ("tenant_id", "environment_id", "idempotency_key");
-- Create index "idx_refund_tenant_payment" to table: "refunds"
CREATE INDEX "idx_refund_tenant_payment" ON "refunds" ("tenant_id", "environment_id", "payment_id");
-- Create index "idx_refund_tenant_status" to table: "refunds"
CREATE INDEX "idx_refund_tenant_status" ON "refunds" ("tenant_id", "environment_id", "refund_status");
-- Create "scheduled_tasks" table
CREATE TABLE "scheduled_tasks" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "connection_id" character varying(50) NOT NULL,
  "entity_type" character varying(50) NOT NULL,
  "interval" character varying(20) NOT NULL,
  "enabled" boolean NOT NULL DEFAULT true,
  "job_config" jsonb NULL,
  "temporal_schedule_id" character varying(100) NULL,
  PRIMARY KEY ("id")
);
-- Create index "scheduledtask_connection_id_enabled" to table: "scheduled_tasks"
CREATE INDEX "scheduledtask_connection_id_enabled" ON "scheduled_tasks" ("connection_id", "enabled");
-- Create index "scheduledtask_connection_id_entity_type_status" to table: "scheduled_tasks"
CREATE INDEX "scheduledtask_connection_id_entity_type_status" ON "scheduled_tasks" ("connection_id", "entity_type", "status");
-- Create index "scheduledtask_entity_type_interval_enabled" to table: "scheduled_tasks"
CREATE INDEX "scheduledtask_entity_type_interval_enabled" ON "scheduled_tasks" ("entity_type", "interval", "enabled");
-- Create index "scheduledtask_tenant_id_environment_id_enabled" to table: "scheduled_tasks"
CREATE INDEX "scheduledtask_tenant_id_environment_id_enabled" ON "scheduled_tasks" ("tenant_id", "environment_id", "enabled");
-- Create "secrets" table
CREATE TABLE "secrets" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "name" character varying NOT NULL,
  "type" character varying NOT NULL,
  "provider" character varying NOT NULL,
  "value" character varying NULL,
  "display_id" character varying NULL,
  "expires_at" timestamptz NULL,
  "last_used_at" timestamptz NULL,
  "provider_data" jsonb NULL,
  "roles" jsonb NULL,
  "user_type" character varying NULL DEFAULT 'user',
  "user_id" character varying NULL,
  PRIMARY KEY ("id")
);
-- Create index "secret_tenant_id_environment_id_provider_status" to table: "secrets"
CREATE INDEX "secret_tenant_id_environment_id_provider_status" ON "secrets" ("tenant_id", "environment_id", "provider", "status");
-- Create index "secret_tenant_id_environment_id_type_status" to table: "secrets"
CREATE INDEX "secret_tenant_id_environment_id_type_status" ON "secrets" ("tenant_id", "environment_id", "type", "status");
-- Create index "secret_type_value_status" to table: "secrets"
CREATE INDEX "secret_type_value_status" ON "secrets" ("type", "value", "status");
-- Create "settings" table
CREATE TABLE "settings" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "key" character varying NOT NULL,
  "value" jsonb NULL,
  PRIMARY KEY ("id")
);
-- Create index "settings_tenant_id_environment_id_status_key" to table: "settings"
CREATE UNIQUE INDEX "settings_tenant_id_environment_id_status_key" ON "settings" ("tenant_id", "environment_id", "status", "key");
-- Create "system_events" table
CREATE TABLE "system_events" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "event_name" character varying(128) NULL DEFAULT '',
  "entity_type" character varying(64) NULL DEFAULT '',
  "entity_id" character varying(50) NULL DEFAULT '',
  "webhook_message_id" character varying(128) NULL,
  "published_at" timestamptz NULL,
  "payload" jsonb NULL,
  "failure_count" bigint NOT NULL DEFAULT 0,
  "failure_reason" text NULL,
  PRIMARY KEY ("id")
);
-- Create index "idx_system_events_tenant_env" to table: "system_events"
CREATE INDEX "idx_system_events_tenant_env" ON "system_events" ("tenant_id", "environment_id");
-- Create "tasks" table
CREATE TABLE "tasks" (
  "id" character varying(100) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "task_type" character varying(50) NOT NULL,
  "entity_type" character varying(50) NOT NULL,
  "scheduled_task_id" character varying(50) NULL,
  "workflow_id" character varying(255) NULL,
  "file_url" character varying(255) NOT NULL DEFAULT '',
  "file_name" character varying(255) NULL,
  "file_type" character varying(10) NOT NULL,
  "task_status" character varying(50) NOT NULL DEFAULT 'PENDING',
  "total_records" bigint NULL,
  "processed_records" bigint NOT NULL DEFAULT 0,
  "successful_records" bigint NOT NULL DEFAULT 0,
  "failed_records" bigint NOT NULL DEFAULT 0,
  "error_summary" text NULL,
  "metadata" jsonb NULL,
  "started_at" timestamptz NULL,
  "completed_at" timestamptz NULL,
  "failed_at" timestamptz NULL,
  PRIMARY KEY ("id")
);
-- Create index "idx_tasks_tenant_env_task_status" to table: "tasks"
CREATE INDEX "idx_tasks_tenant_env_task_status" ON "tasks" ("tenant_id", "environment_id", "task_status", "status");
-- Create index "idx_tasks_tenant_env_type_status" to table: "tasks"
CREATE INDEX "idx_tasks_tenant_env_type_status" ON "tasks" ("tenant_id", "environment_id", "task_type", "entity_type", "status");
-- Create index "idx_tasks_tenant_env_user" to table: "tasks"
CREATE INDEX "idx_tasks_tenant_env_user" ON "tasks" ("tenant_id", "environment_id", "created_by", "status");
-- Create "tax_applieds" table
CREATE TABLE "tax_applieds" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "tax_rate_id" character varying(50) NOT NULL,
  "entity_type" character varying(50) NOT NULL,
  "entity_id" character varying(50) NOT NULL,
  "tax_association_id" character varying(50) NULL,
  "taxable_amount" numeric(15,6) NOT NULL,
  "tax_amount" numeric(15,6) NOT NULL,
  "currency" character varying(3) NOT NULL,
  "applied_at" timestamptz NOT NULL,
  "metadata" jsonb NULL,
  "idempotency_key" character varying(50) NULL,
  PRIMARY KEY ("id")
);
-- Create index "idx_entity_tax_association_lookup" to table: "tax_applieds"
CREATE INDEX "idx_entity_tax_association_lookup" ON "tax_applieds" ("tenant_id", "environment_id", "entity_type", "entity_id");
-- Create index "idx_entity_tax_rate_id" to table: "tax_applieds"
CREATE UNIQUE INDEX "idx_entity_tax_rate_id" ON "tax_applieds" ("tenant_id", "environment_id", "entity_type", "entity_id", "tax_rate_id");
-- Create "tax_associations" table
CREATE TABLE "tax_associations" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "tax_rate_id" character varying(50) NOT NULL,
  "entity_type" character varying(50) NOT NULL,
  "entity_id" character varying(50) NOT NULL,
  "priority" integer NOT NULL DEFAULT 100,
  "auto_apply" boolean NOT NULL DEFAULT true,
  "currency" character varying(100) NULL,
  "metadata" jsonb NULL,
  "start_date" timestamptz NULL,
  "end_date" timestamptz NULL,
  PRIMARY KEY ("id")
);
-- Create index "idx_entity_lookup_active" to table: "tax_associations"
CREATE INDEX "idx_entity_lookup_active" ON "tax_associations" ("tenant_id", "environment_id", "entity_type", "entity_id", "status");
-- Create index "idx_tax_rate_id_tenant_id_environment_id" to table: "tax_associations"
CREATE INDEX "idx_tax_rate_id_tenant_id_environment_id" ON "tax_associations" ("tenant_id", "environment_id", "tax_rate_id");
-- Create "tax_rates" table
CREATE TABLE "tax_rates" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "name" character varying NOT NULL,
  "description" character varying NULL,
  "code" character varying NOT NULL,
  "tax_rate_status" character varying NOT NULL,
  "tax_rate_type" character varying NOT NULL DEFAULT 'percentage',
  "scope" character varying NOT NULL,
  "percentage_value" numeric(9,6) NULL,
  "fixed_value" numeric(9,6) NULL,
  "metadata" jsonb NULL,
  PRIMARY KEY ("id")
);
-- Create index "idx_code_tenant_id_environment_id" to table: "tax_rates"
CREATE UNIQUE INDEX "idx_code_tenant_id_environment_id" ON "tax_rates" ("tenant_id", "environment_id", "code") WHERE ((code IS NOT NULL) AND ((code)::text <> ''::text) AND ((status)::text = 'published'::text));
-- Create "tenants" table
CREATE TABLE "tenants" (
  "id" character varying(50) NOT NULL,
  "name" character varying(100) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "internal_status" character varying(20) NOT NULL DEFAULT 'trialing',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "billing_details" jsonb NULL,
  "metadata" jsonb NULL,
  PRIMARY KEY ("id")
);
-- Create index "idx_tenant_created_at" to table: "tenants"
CREATE INDEX "idx_tenant_created_at" ON "tenants" ("created_at");
-- Create "usage_records" table
CREATE TABLE "usage_records" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "customer_id" character varying(50) NOT NULL,
  "customer_external_id" character varying(255) NULL,
  "subscription_id" character varying(50) NOT NULL,
  "plan_id" character varying(50) NOT NULL,
  "quantity" numeric(20,8) NOT NULL,
  "amount" numeric(20,8) NOT NULL,
  "currency" character varying(10) NOT NULL,
  "period_start" timestamptz NOT NULL,
  "period_end" timestamptz NOT NULL,
  "syncs" jsonb NULL,
  "all_providers_synced" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id")
);
-- Create index "usagerecord_tenant_id_environment_id_all_providers_synced" to table: "usage_records"
CREATE INDEX "usagerecord_tenant_id_environment_id_all_providers_synced" ON "usage_records" ("tenant_id", "environment_id", "all_providers_synced");
-- Create "users" table
CREATE TABLE "users" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "metadata" jsonb NULL,
  "email" character varying(255) NULL,
  "name" character varying(255) NULL,
  "type" character varying NOT NULL DEFAULT 'user',
  "roles" jsonb NULL,
  PRIMARY KEY ("id")
);
-- Create index "idx_user_email_unique" to table: "users"
CREATE UNIQUE INDEX "idx_user_email_unique" ON "users" ("email") WHERE (((status)::text = 'published'::text) AND (email IS NOT NULL) AND ((email)::text <> ''::text));
-- Create index "idx_user_tenant_created_at" to table: "users"
CREATE INDEX "idx_user_tenant_created_at" ON "users" ("tenant_id", "created_at");
-- Create index "idx_user_tenant_status" to table: "users"
CREATE INDEX "idx_user_tenant_status" ON "users" ("tenant_id", "status", "type");
-- Create "wallet_transactions" table
CREATE TABLE "wallet_transactions" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "wallet_id" character varying(50) NOT NULL,
  "customer_id" character varying(50) NULL,
  "type" character varying NOT NULL DEFAULT 'credit',
  "amount" numeric(20,9) NOT NULL,
  "credit_amount" numeric(20,9) NOT NULL DEFAULT 0,
  "credit_balance_before" numeric(20,9) NOT NULL DEFAULT 0,
  "credit_balance_after" numeric(20,9) NOT NULL DEFAULT 0,
  "reference_type" character varying(50) NULL,
  "reference_id" character varying NULL,
  "description" character varying NULL,
  "metadata" jsonb NULL,
  "transaction_status" character varying(50) NOT NULL DEFAULT 'pending',
  "expiry_date" timestamp NULL,
  "credits_available" numeric(20,9) NOT NULL,
  "currency" character varying(10) NOT NULL,
  "conversion_rate" numeric(10,5) NULL,
  "topup_conversion_rate" numeric(10,5) NULL,
  "idempotency_key" character varying NULL,
  "transaction_reason" character varying(50) NOT NULL DEFAULT 'FREE_CREDIT_GRANT',
  "priority" bigint NULL,
  "parent_transaction_id" character varying(50) NULL,
  PRIMARY KEY ("id")
);
-- Create index "idx_tenant_environment_idempotency_key" to table: "wallet_transactions"
CREATE UNIQUE INDEX "idx_tenant_environment_idempotency_key" ON "wallet_transactions" ("tenant_id", "environment_id", "idempotency_key") WHERE ((idempotency_key IS NOT NULL) AND ((idempotency_key)::text <> ''::text) AND ((status)::text = 'published'::text));
-- Create index "idx_tenant_environment_parent_transaction_status" to table: "wallet_transactions"
CREATE INDEX "idx_tenant_environment_parent_transaction_status" ON "wallet_transactions" ("tenant_id", "environment_id", "parent_transaction_id", "transaction_status");
-- Create index "idx_tenant_wallet_type_credits_available_expiry_date" to table: "wallet_transactions"
CREATE INDEX "idx_tenant_wallet_type_credits_available_expiry_date" ON "wallet_transactions" ("tenant_id", "environment_id", "wallet_id", "type", "credits_available", "expiry_date") WHERE ((credits_available > (0)::numeric) AND ((type)::text = 'credit'::text));
-- Create index "wallettransaction_tenant_id_environment_id_created_at" to table: "wallet_transactions"
CREATE INDEX "wallettransaction_tenant_id_environment_id_created_at" ON "wallet_transactions" ("tenant_id", "environment_id", "created_at");
-- Create index "wallettransaction_tenant_id_environment_id_customer_id" to table: "wallet_transactions"
CREATE INDEX "wallettransaction_tenant_id_environment_id_customer_id" ON "wallet_transactions" ("tenant_id", "environment_id", "customer_id");
-- Create index "wallettransaction_tenant_id_environment_id_reference_type_refer" to table: "wallet_transactions"
CREATE INDEX "wallettransaction_tenant_id_environment_id_reference_type_refer" ON "wallet_transactions" ("tenant_id", "environment_id", "reference_type", "reference_id", "status");
-- Create index "wallettransaction_tenant_id_environment_id_wallet_id" to table: "wallet_transactions"
CREATE INDEX "wallettransaction_tenant_id_environment_id_wallet_id" ON "wallet_transactions" ("tenant_id", "environment_id", "wallet_id");
-- Create "wallets" table
CREATE TABLE "wallets" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "name" character varying(255) NULL,
  "customer_id" character varying(50) NOT NULL,
  "currency" character varying(10) NOT NULL,
  "description" character varying NULL,
  "metadata" jsonb NULL,
  "balance" numeric(20,9) NOT NULL,
  "credit_balance" numeric(20,9) NOT NULL DEFAULT 0,
  "wallet_status" character varying(50) NOT NULL DEFAULT 'active',
  "auto_topup" jsonb NULL,
  "wallet_type" character varying(50) NOT NULL DEFAULT 'PRE_PAID',
  "conversion_rate" numeric(10,5) NOT NULL,
  "topup_conversion_rate" numeric(10,5) NULL,
  "config" jsonb NULL,
  "alert_settings" jsonb NULL,
  "alert_state" character varying(50) NULL DEFAULT 'ok',
  PRIMARY KEY ("id")
);
-- Create index "wallet_tenant_id_environment_id_customer_id_status" to table: "wallets"
CREATE INDEX "wallet_tenant_id_environment_id_customer_id_status" ON "wallets" ("tenant_id", "environment_id", "customer_id", "status");
-- Create index "wallet_tenant_id_environment_id_status_wallet_status" to table: "wallets"
CREATE INDEX "wallet_tenant_id_environment_id_status_wallet_status" ON "wallets" ("tenant_id", "environment_id", "status", "wallet_status");
-- Create "workflow_executions" table
CREATE TABLE "workflow_executions" (
  "id" character varying(26) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "workflow_id" character varying(255) NOT NULL,
  "run_id" character varying(255) NOT NULL,
  "workflow_type" character varying(100) NOT NULL,
  "task_queue" character varying(100) NOT NULL,
  "start_time" timestamptz NOT NULL,
  "end_time" timestamptz NULL,
  "duration_ms" bigint NULL,
  "workflow_status" character varying(50) NOT NULL DEFAULT 'Running',
  "entity" character varying(100) NULL,
  "entity_id" character varying(255) NULL,
  "metadata" jsonb NULL,
  PRIMARY KEY ("id")
);
-- Create index "idx_workflow_executions_start_time" to table: "workflow_executions"
CREATE INDEX "idx_workflow_executions_start_time" ON "workflow_executions" ("start_time");
-- Create index "idx_workflow_executions_tenant_env_entity" to table: "workflow_executions"
CREATE INDEX "idx_workflow_executions_tenant_env_entity" ON "workflow_executions" ("tenant_id", "environment_id", "entity", "entity_id");
-- Create index "idx_workflow_executions_tenant_env_queue" to table: "workflow_executions"
CREATE INDEX "idx_workflow_executions_tenant_env_queue" ON "workflow_executions" ("tenant_id", "environment_id", "task_queue");
-- Create index "idx_workflow_executions_tenant_env_status" to table: "workflow_executions"
CREATE INDEX "idx_workflow_executions_tenant_env_status" ON "workflow_executions" ("tenant_id", "environment_id", "workflow_status");
-- Create index "idx_workflow_executions_tenant_env_time" to table: "workflow_executions"
CREATE INDEX "idx_workflow_executions_tenant_env_time" ON "workflow_executions" ("tenant_id", "environment_id", "start_time");
-- Create index "idx_workflow_executions_tenant_env_type" to table: "workflow_executions"
CREATE INDEX "idx_workflow_executions_tenant_env_type" ON "workflow_executions" ("tenant_id", "environment_id", "workflow_type");
-- Create index "idx_workflow_executions_workflow_run_unique" to table: "workflow_executions"
CREATE UNIQUE INDEX "idx_workflow_executions_workflow_run_unique" ON "workflow_executions" ("workflow_id", "run_id");
-- Create "prices" table
CREATE TABLE "prices" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "display_name" character varying(255) NULL,
  "amount" numeric(25,15) NOT NULL,
  "currency" character varying(3) NOT NULL,
  "display_amount" character varying(255) NULL,
  "price_unit_type" character varying(20) NOT NULL DEFAULT 'FIAT',
  "price_unit" character varying(3) NULL,
  "price_unit_amount" numeric(25,15) NULL,
  "display_price_unit_amount" character varying(255) NULL,
  "conversion_rate" numeric(25,15) NULL,
  "min_quantity" numeric(20,8) NULL,
  "type" character varying(20) NOT NULL,
  "billing_period" character varying(20) NOT NULL,
  "billing_period_count" bigint NOT NULL,
  "billing_model" character varying(20) NOT NULL,
  "billing_cadence" character varying(20) NOT NULL DEFAULT 'RECURRING',
  "invoice_cadence" character varying(20) NULL,
  "trial_period_days" bigint NOT NULL DEFAULT 0,
  "meter_id" character varying(50) NULL,
  "filter_values" jsonb NULL,
  "tier_mode" character varying(20) NULL,
  "tiers" jsonb NULL,
  "price_unit_tiers" jsonb NULL,
  "transform_quantity" jsonb NULL,
  "lookup_key" character varying(255) NULL,
  "description" text NULL,
  "metadata" jsonb NULL,
  "entity_type" character varying(20) NOT NULL DEFAULT 'PLAN',
  "entity_id" character varying(50) NOT NULL,
  "parent_price_id" character varying(50) NULL,
  "start_date" timestamptz NULL,
  "end_date" timestamptz NULL,
  "group_id" character varying(50) NULL,
  "sequence" bigserial NOT NULL,
  "price_unit_id" character varying(50) NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "prices_price_units_price_unit_edge" FOREIGN KEY ("price_unit_id") REFERENCES "price_units" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "price_start_date_end_date" to table: "prices"
CREATE INDEX "price_start_date_end_date" ON "prices" ("start_date", "end_date");
-- Create index "price_tenant_id_environment_id" to table: "prices"
CREATE INDEX "price_tenant_id_environment_id" ON "prices" ("tenant_id", "environment_id");
-- Create index "price_tenant_id_environment_id_entity_id_entity_type_sequence" to table: "prices"
CREATE INDEX "price_tenant_id_environment_id_entity_id_entity_type_sequence" ON "prices" ("tenant_id", "environment_id", "entity_id", "entity_type", "sequence") WHERE ((status)::text = 'published'::text);
-- Create index "price_tenant_id_environment_id_group_id" to table: "prices"
CREATE INDEX "price_tenant_id_environment_id_group_id" ON "prices" ("tenant_id", "environment_id", "group_id");
-- Create index "price_tenant_id_environment_id_lookup_key" to table: "prices"
CREATE UNIQUE INDEX "price_tenant_id_environment_id_lookup_key" ON "prices" ("tenant_id", "environment_id", "lookup_key") WHERE (((status)::text = 'published'::text) AND (lookup_key IS NOT NULL) AND ((lookup_key)::text <> ''::text) AND (end_date IS NULL));
-- Create "costsheets" table
CREATE TABLE "costsheets" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "metadata" jsonb NULL,
  "name" character varying(255) NOT NULL,
  "lookup_key" character varying(255) NULL,
  "description" text NULL,
  "price_costsheet" character varying(50) NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "costsheets_prices_costsheet" FOREIGN KEY ("price_costsheet") REFERENCES "prices" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "costsheet_tenant_id_environment_id" to table: "costsheets"
CREATE INDEX "costsheet_tenant_id_environment_id" ON "costsheets" ("tenant_id", "environment_id");
-- Create index "idx_costsheet_tenant_environment_lookup_key" to table: "costsheets"
CREATE UNIQUE INDEX "idx_costsheet_tenant_environment_lookup_key" ON "costsheets" ("tenant_id", "environment_id", "lookup_key") WHERE (((status)::text = 'published'::text) AND (lookup_key IS NOT NULL) AND ((lookup_key)::text <> ''::text));
-- Create "coupons" table
CREATE TABLE "coupons" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "name" character varying(255) NOT NULL,
  "redeem_after" timestamptz NULL,
  "redeem_before" timestamptz NULL,
  "max_redemptions" bigint NULL,
  "total_redemptions" bigint NOT NULL DEFAULT 0,
  "rules" jsonb NULL,
  "amount_off" numeric(20,8) NULL,
  "percentage_off" numeric(7,4) NULL,
  "type" character varying(20) NOT NULL DEFAULT 'fixed',
  "cadence" character varying(20) NOT NULL DEFAULT 'once',
  "duration_in_periods" bigint NULL,
  "currency" character varying(10) NULL,
  "metadata" jsonb NULL,
  "coupon_code" character varying(100) NULL,
  PRIMARY KEY ("id")
);
-- Create index "coupon_tenant_id_environment_id" to table: "coupons"
CREATE INDEX "coupon_tenant_id_environment_id" ON "coupons" ("tenant_id", "environment_id");
-- Create index "idx_coupon_tenant_environment_coupon_code_unique" to table: "coupons"
CREATE UNIQUE INDEX "idx_coupon_tenant_environment_coupon_code_unique" ON "coupons" ("tenant_id", "environment_id", "coupon_code") WHERE ((coupon_code IS NOT NULL) AND ((coupon_code)::text <> ''::text) AND ((status)::text = 'published'::text));
-- Create "invoices" table
CREATE TABLE "invoices" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "customer_id" character varying(50) NOT NULL,
  "subscription_id" character varying(50) NULL,
  "subscription_customer_id" character varying(50) NULL,
  "invoice_type" character varying(50) NOT NULL,
  "invoice_status" character varying(50) NOT NULL DEFAULT 'DRAFT',
  "payment_status" character varying(50) NOT NULL DEFAULT 'PENDING',
  "currency" character varying(10) NOT NULL,
  "amount_due" numeric(20,8) NOT NULL,
  "amount_paid" numeric(20,8) NOT NULL,
  "amount_remaining" numeric(20,8) NOT NULL,
  "subtotal" numeric(20,8) NULL,
  "adjustment_amount" numeric(20,8) NULL,
  "refunded_amount" numeric(20,8) NULL,
  "total_tax" numeric(20,8) NULL,
  "total_discount" numeric(20,8) NULL,
  "total" numeric(20,8) NULL,
  "description" character varying NULL,
  "due_date" timestamptz NULL,
  "paid_at" timestamptz NULL,
  "voided_at" timestamptz NULL,
  "finalized_at" timestamptz NULL,
  "issue_date" timestamptz NULL,
  "last_computed_at" timestamptz NULL,
  "billing_period" character varying NULL,
  "period_start" timestamptz NULL,
  "period_end" timestamptz NULL,
  "invoice_pdf_url" character varying NULL,
  "billing_reason" character varying NULL,
  "metadata" jsonb NULL,
  "version" bigint NOT NULL DEFAULT 1,
  "invoice_number" character varying(50) NULL,
  "billing_sequence" integer NULL,
  "total_prepaid_credits_applied" numeric(20,8) NULL,
  "idempotency_key" character varying(100) NULL,
  "recalculated_invoice_id" character varying NULL,
  PRIMARY KEY ("id")
);
-- Create index "idx_subscription_period_unique" to table: "invoices"
CREATE INDEX "idx_subscription_period_unique" ON "invoices" ("subscription_id", "period_start", "period_end") WHERE (((invoice_status)::text <> 'VOIDED'::text) AND (subscription_id IS NOT NULL));
-- Create index "idx_tenant_customer_status" to table: "invoices"
CREATE INDEX "idx_tenant_customer_status" ON "invoices" ("tenant_id", "environment_id", "customer_id", "invoice_status", "payment_status", "status") WHERE ((status)::text = 'published'::text);
-- Create index "idx_tenant_due_date_status" to table: "invoices"
CREATE INDEX "idx_tenant_due_date_status" ON "invoices" ("tenant_id", "environment_id", "due_date", "invoice_status", "payment_status", "status");
-- Create index "idx_tenant_environment_idempotency_key_unique" to table: "invoices"
CREATE UNIQUE INDEX "idx_tenant_environment_idempotency_key_unique" ON "invoices" ("tenant_id", "environment_id", "idempotency_key") WHERE ((idempotency_key IS NOT NULL) AND ((status)::text = 'published'::text) AND ((invoice_status)::text <> 'VOIDED'::text));
-- Create index "idx_tenant_environment_invoice_number_unique" to table: "invoices"
CREATE UNIQUE INDEX "idx_tenant_environment_invoice_number_unique" ON "invoices" ("tenant_id", "environment_id", "invoice_number") WHERE ((invoice_number IS NOT NULL) AND ((invoice_number)::text <> ''::text) AND ((status)::text = 'published'::text));
-- Create index "idx_tenant_subscription_status" to table: "invoices"
CREATE INDEX "idx_tenant_subscription_status" ON "invoices" ("tenant_id", "environment_id", "subscription_id", "invoice_status", "payment_status", "status");
-- Create index "idx_tenant_type_status" to table: "invoices"
CREATE INDEX "idx_tenant_type_status" ON "invoices" ("tenant_id", "environment_id", "invoice_type", "invoice_status", "payment_status", "status");
-- Create "invoice_line_items" table
CREATE TABLE "invoice_line_items" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "customer_id" character varying(50) NOT NULL,
  "subscription_id" character varying(50) NULL,
  "entity_id" character varying(50) NULL,
  "entity_type" character varying(50) NULL,
  "plan_display_name" character varying NULL,
  "price_id" character varying(50) NULL,
  "price_type" character varying(50) NULL,
  "meter_id" character varying(50) NULL,
  "meter_display_name" character varying NULL,
  "price_unit_id" character varying(50) NULL,
  "price_unit" character varying(3) NULL,
  "price_unit_amount" numeric(20,8) NULL,
  "display_name" character varying NULL,
  "amount" numeric(20,8) NOT NULL,
  "quantity" numeric(20,8) NOT NULL,
  "currency" character varying(10) NOT NULL,
  "period_start" timestamptz NULL,
  "period_end" timestamptz NULL,
  "metadata" jsonb NULL,
  "commitment_info" jsonb NULL,
  "prepaid_credits_applied" numeric(20,8) NULL,
  "line_item_discount" numeric(20,8) NULL,
  "invoice_level_discount" numeric(20,8) NULL,
  "subscription_line_item_id" character varying(50) NULL,
  "adjusted_entitlement_quantity" numeric(20,8) NULL,
  "invoice_id" character varying(50) NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "invoice_line_items_invoices_line_items" FOREIGN KEY ("invoice_id") REFERENCES "invoices" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "invoicelineitem_period_start_period_end" to table: "invoice_line_items"
CREATE INDEX "invoicelineitem_period_start_period_end" ON "invoice_line_items" ("period_start", "period_end");
-- Create index "invoicelineitem_subscription_id_status" to table: "invoice_line_items"
CREATE INDEX "invoicelineitem_subscription_id_status" ON "invoice_line_items" ("subscription_id", "status");
-- Create index "invoicelineitem_tenant_id_environment_id_customer_id_status" to table: "invoice_line_items"
CREATE INDEX "invoicelineitem_tenant_id_environment_id_customer_id_status" ON "invoice_line_items" ("tenant_id", "environment_id", "customer_id", "status");
-- Create index "invoicelineitem_tenant_id_environment_id_invoice_id_status" to table: "invoice_line_items"
CREATE INDEX "invoicelineitem_tenant_id_environment_id_invoice_id_status" ON "invoice_line_items" ("tenant_id", "environment_id", "invoice_id", "status");
-- Create index "invoicelineitem_tenant_id_environment_id_meter_id_status" to table: "invoice_line_items"
CREATE INDEX "invoicelineitem_tenant_id_environment_id_meter_id_status" ON "invoice_line_items" ("tenant_id", "environment_id", "meter_id", "status");
-- Create index "invoicelineitem_tenant_id_environment_id_price_id_status" to table: "invoice_line_items"
CREATE INDEX "invoicelineitem_tenant_id_environment_id_price_id_status" ON "invoice_line_items" ("tenant_id", "environment_id", "price_id", "status");
-- Create index "invoicelineitem_tenant_id_environment_id_subscription_id_status" to table: "invoice_line_items"
CREATE INDEX "invoicelineitem_tenant_id_environment_id_subscription_id_status" ON "invoice_line_items" ("tenant_id", "environment_id", "subscription_id", "status");
-- Create "customers" table
CREATE TABLE "customers" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "metadata" jsonb NULL,
  "external_id" character varying(255) NOT NULL,
  "name" character varying(255) NOT NULL,
  "email" character varying(255) NULL,
  "contact" character varying(20) NULL,
  "address_line1" character varying(255) NULL,
  "address_line2" character varying(255) NULL,
  "address_city" character varying(100) NULL,
  "address_state" character varying(100) NULL,
  "address_postal_code" character varying(20) NULL,
  "address_country" character varying(2) NULL,
  "timezone" character varying(50) NULL DEFAULT 'UTC',
  PRIMARY KEY ("id")
);
-- Create index "customer_tenant_id_environment_id" to table: "customers"
CREATE INDEX "customer_tenant_id_environment_id" ON "customers" ("tenant_id", "environment_id");
-- Create index "idx_customer_metadata_gin" to table: "customers"
CREATE INDEX "idx_customer_metadata_gin" ON "customers" USING GIN ("metadata");
-- Create index "idx_customer_tenant_environment_email" to table: "customers"
CREATE INDEX "idx_customer_tenant_environment_email" ON "customers" ("tenant_id", "environment_id", "email") WHERE ((email IS NOT NULL) AND ((email)::text <> ''::text) AND ((status)::text = 'published'::text));
-- Create index "idx_tenant_environment_external_id_unique" to table: "customers"
CREATE UNIQUE INDEX "idx_tenant_environment_external_id_unique" ON "customers" ("tenant_id", "environment_id", "external_id") WHERE ((external_id IS NOT NULL) AND ((external_id)::text <> ''::text) AND ((status)::text = 'published'::text));
-- Create "subscriptions" table
CREATE TABLE "subscriptions" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "lookup_key" character varying NULL,
  "customer_id" character varying(50) NOT NULL,
  "plan_id" character varying(50) NOT NULL,
  "subscription_status" character varying(50) NOT NULL DEFAULT 'active',
  "currency" character varying(10) NOT NULL,
  "billing_anchor" timestamptz NOT NULL,
  "start_date" timestamptz NOT NULL,
  "end_date" timestamptz NULL,
  "current_period_start" timestamptz NOT NULL,
  "current_period_end" timestamptz NOT NULL,
  "cancelled_at" timestamptz NULL,
  "cancel_at" timestamptz NULL,
  "cancel_at_period_end" boolean NOT NULL DEFAULT false,
  "trial_start" timestamptz NULL,
  "trial_end" timestamptz NULL,
  "billing_cadence" character varying NOT NULL,
  "billing_period" character varying NOT NULL,
  "billing_period_count" bigint NOT NULL DEFAULT 1,
  "version" bigint NOT NULL DEFAULT 1,
  "metadata" jsonb NULL,
  "pause_status" character varying(50) NOT NULL DEFAULT 'none',
  "active_pause_id" character varying(50) NULL,
  "billing_cycle" character varying NOT NULL DEFAULT 'anniversary',
  "commitment_amount" numeric(20,6) NULL,
  "commitment_duration" character varying(50) NULL,
  "overage_factor" numeric(10,6) NULL,
  "payment_behavior" character varying(50) NOT NULL DEFAULT 'default_active',
  "collection_method" character varying(50) NOT NULL DEFAULT 'charge_automatically',
  "gateway_payment_method_id" character varying(255) NULL,
  "timezone" character varying NOT NULL DEFAULT 'UTC',
  "proration_behavior" character varying NOT NULL DEFAULT 'none',
  "enable_true_up" boolean NOT NULL DEFAULT false,
  "parent_subscription_id" character varying(50) NULL,
  "payment_terms" character varying(20) NULL,
  "subscription_type" character varying(20) NOT NULL DEFAULT 'standalone',
  "auto_invoice_threshold" numeric(20,6) NULL,
  "synced_price_sequence" bigint NOT NULL DEFAULT 0,
  "invoicing_customer_id" character varying(50) NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "subscriptions_customers_invoicing_customer" FOREIGN KEY ("invoicing_customer_id") REFERENCES "customers" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "subscription_tenant_id_environment_id_current_period_end_subscr" to table: "subscriptions"
CREATE INDEX "subscription_tenant_id_environment_id_current_period_end_subscr" ON "subscriptions" ("tenant_id", "environment_id", "current_period_end", "subscription_status", "status");
-- Create index "subscription_tenant_id_environment_id_customer_id_status" to table: "subscriptions"
CREATE INDEX "subscription_tenant_id_environment_id_customer_id_status" ON "subscriptions" ("tenant_id", "environment_id", "customer_id", "status") WHERE ((status)::text = 'published'::text);
-- Create index "subscription_tenant_id_environment_id_plan_id_status" to table: "subscriptions"
CREATE INDEX "subscription_tenant_id_environment_id_plan_id_status" ON "subscriptions" ("tenant_id", "environment_id", "plan_id", "status");
-- Create index "subscription_tenant_id_environment_id_plan_id_synced_price_sequ" to table: "subscriptions"
CREATE INDEX "subscription_tenant_id_environment_id_plan_id_synced_price_sequ" ON "subscriptions" ("tenant_id", "environment_id", "plan_id", "synced_price_sequence") WHERE (((status)::text = 'published'::text) AND ((subscription_type)::text = ANY (ARRAY[('standalone'::character varying)::text, ('delegated_invoicing'::character varying)::text, ('parent'::character varying)::text, ('grouped_invoicing'::character varying)::text])));
-- Create index "subscription_tenant_id_environment_id_subscription_status_statu" to table: "subscriptions"
CREATE INDEX "subscription_tenant_id_environment_id_subscription_status_statu" ON "subscriptions" ("tenant_id", "environment_id", "subscription_status", "status");
-- Create "coupon_applications" table
CREATE TABLE "coupon_applications" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "coupon_association_id" character varying(50) NULL,
  "applied_at" timestamptz NOT NULL,
  "original_price" numeric(20,8) NOT NULL,
  "final_price" numeric(20,8) NOT NULL,
  "discounted_amount" numeric(20,8) NOT NULL,
  "discount_type" character varying(20) NOT NULL,
  "discount_percentage" numeric(7,4) NULL,
  "currency" character varying(10) NULL,
  "coupon_snapshot" jsonb NULL,
  "metadata" jsonb NULL,
  "coupon_id" character varying(50) NOT NULL,
  "invoice_id" character varying(50) NOT NULL,
  "invoice_line_item_id" character varying(50) NULL,
  "subscription_id" character varying(50) NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "coupon_applications_coupons_coupon_applications" FOREIGN KEY ("coupon_id") REFERENCES "coupons" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "coupon_applications_invoice_line_items_coupon_applications" FOREIGN KEY ("invoice_line_item_id") REFERENCES "invoice_line_items" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "coupon_applications_invoices_coupon_applications" FOREIGN KEY ("invoice_id") REFERENCES "invoices" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "coupon_applications_subscriptions_coupon_applications" FOREIGN KEY ("subscription_id") REFERENCES "subscriptions" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "couponapplication_tenant_id_environment_id" to table: "coupon_applications"
CREATE INDEX "couponapplication_tenant_id_environment_id" ON "coupon_applications" ("tenant_id", "environment_id");
-- Create index "couponapplication_tenant_id_environment_id_coupon_id" to table: "coupon_applications"
CREATE INDEX "couponapplication_tenant_id_environment_id_coupon_id" ON "coupon_applications" ("tenant_id", "environment_id", "coupon_id");
-- Create index "couponapplication_tenant_id_environment_id_invoice_id" to table: "coupon_applications"
CREATE INDEX "couponapplication_tenant_id_environment_id_invoice_id" ON "coupon_applications" ("tenant_id", "environment_id", "invoice_id");
-- Create index "couponapplication_tenant_id_environment_id_invoice_id_invoice_l" to table: "coupon_applications"
CREATE INDEX "couponapplication_tenant_id_environment_id_invoice_id_invoice_l" ON "coupon_applications" ("tenant_id", "environment_id", "invoice_id", "invoice_line_item_id");
-- Create index "couponapplication_tenant_id_environment_id_subscription_id" to table: "coupon_applications"
CREATE INDEX "couponapplication_tenant_id_environment_id_subscription_id" ON "coupon_applications" ("tenant_id", "environment_id", "subscription_id");
-- Create index "couponapplication_tenant_id_environment_id_subscription_id_coup" to table: "coupon_applications"
CREATE INDEX "couponapplication_tenant_id_environment_id_subscription_id_coup" ON "coupon_applications" ("tenant_id", "environment_id", "subscription_id", "coupon_id");
-- Create "subscription_line_items" table
CREATE TABLE "subscription_line_items" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "customer_id" character varying(50) NOT NULL,
  "entity_id" character varying(50) NULL,
  "entity_type" character varying(50) NOT NULL DEFAULT 'plan',
  "plan_display_name" character varying NULL,
  "price_id" character varying(50) NOT NULL,
  "price_type" character varying(50) NULL,
  "meter_id" character varying(50) NULL,
  "meter_display_name" character varying NULL,
  "price_unit_id" character varying(50) NULL,
  "price_unit" character varying(3) NULL,
  "display_name" character varying NULL,
  "quantity" numeric(20,8) NOT NULL,
  "currency" character varying(10) NOT NULL,
  "billing_period" character varying(50) NOT NULL,
  "billing_period_count" bigint NOT NULL DEFAULT 1,
  "invoice_cadence" character varying(20) NULL,
  "start_date" timestamptz NULL,
  "end_date" timestamptz NULL,
  "subscription_phase_id" character varying(50) NULL,
  "addon_association_id" character varying(50) NULL,
  "metadata" jsonb NULL,
  "commitment_amount" numeric(20,8) NULL,
  "commitment_quantity" numeric(20,8) NULL,
  "commitment_type" character varying(20) NULL,
  "commitment_overage_factor" numeric(10,4) NULL,
  "commitment_true_up_enabled" boolean NOT NULL DEFAULT false,
  "commitment_windowed" boolean NOT NULL DEFAULT false,
  "commitment_duration" character varying(50) NULL,
  "commitment_time_buckets" jsonb NULL,
  "subscription_id" character varying(50) NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "subscription_line_items_subscriptions_line_items" FOREIGN KEY ("subscription_id") REFERENCES "subscriptions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "subscriptionlineitem_start_date_end_date" to table: "subscription_line_items"
CREATE INDEX "subscriptionlineitem_start_date_end_date" ON "subscription_line_items" ("start_date", "end_date");
-- Create index "subscriptionlineitem_subscription_id_status" to table: "subscription_line_items"
CREATE INDEX "subscriptionlineitem_subscription_id_status" ON "subscription_line_items" ("subscription_id", "status");
-- Create index "subscriptionlineitem_tenant_id_environment_id_customer_id_statu" to table: "subscription_line_items"
CREATE INDEX "subscriptionlineitem_tenant_id_environment_id_customer_id_statu" ON "subscription_line_items" ("tenant_id", "environment_id", "customer_id", "status");
-- Create index "subscriptionlineitem_tenant_id_environment_id_entity_id_entity_" to table: "subscription_line_items"
CREATE INDEX "subscriptionlineitem_tenant_id_environment_id_entity_id_entity_" ON "subscription_line_items" ("tenant_id", "environment_id", "entity_id", "entity_type", "status");
-- Create index "subscriptionlineitem_tenant_id_environment_id_meter_id_status" to table: "subscription_line_items"
CREATE INDEX "subscriptionlineitem_tenant_id_environment_id_meter_id_status" ON "subscription_line_items" ("tenant_id", "environment_id", "meter_id", "status");
-- Create index "subscriptionlineitem_tenant_id_environment_id_price_id_status" to table: "subscription_line_items"
CREATE INDEX "subscriptionlineitem_tenant_id_environment_id_price_id_status" ON "subscription_line_items" ("tenant_id", "environment_id", "price_id", "status");
-- Create index "subscriptionlineitem_tenant_id_environment_id_subscription_id_s" to table: "subscription_line_items"
CREATE INDEX "subscriptionlineitem_tenant_id_environment_id_subscription_id_s" ON "subscription_line_items" ("tenant_id", "environment_id", "subscription_id", "status");
-- Create "coupon_associations" table
CREATE TABLE "coupon_associations" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "subscription_phase_id" character varying(50) NULL,
  "start_date" timestamptz NOT NULL,
  "end_date" timestamptz NULL,
  "metadata" jsonb NULL,
  "coupon_id" character varying(50) NOT NULL,
  "subscription_id" character varying(50) NOT NULL,
  "subscription_line_item_id" character varying(50) NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "coupon_associations_coupons_coupon_associations" FOREIGN KEY ("coupon_id") REFERENCES "coupons" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "coupon_associations_subscription_line_items_coupon_associations" FOREIGN KEY ("subscription_line_item_id") REFERENCES "subscription_line_items" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "coupon_associations_subscriptions_coupon_associations" FOREIGN KEY ("subscription_id") REFERENCES "subscriptions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "couponassociation_tenant_id_environment_id" to table: "coupon_associations"
CREATE INDEX "couponassociation_tenant_id_environment_id" ON "coupon_associations" ("tenant_id", "environment_id");
-- Create index "couponassociation_tenant_id_environment_id_coupon_id" to table: "coupon_associations"
CREATE INDEX "couponassociation_tenant_id_environment_id_coupon_id" ON "coupon_associations" ("tenant_id", "environment_id", "coupon_id");
-- Create index "couponassociation_tenant_id_environment_id_subscription_id" to table: "coupon_associations"
CREATE INDEX "couponassociation_tenant_id_environment_id_subscription_id" ON "coupon_associations" ("tenant_id", "environment_id", "subscription_id");
-- Create index "couponassociation_tenant_id_environment_id_subscription_id_subs" to table: "coupon_associations"
CREATE INDEX "couponassociation_tenant_id_environment_id_subscription_id_subs" ON "coupon_associations" ("tenant_id", "environment_id", "subscription_id", "subscription_line_item_id");
-- Create "coupon_association_coupon_applications" table
CREATE TABLE "coupon_association_coupon_applications" (
  "coupon_association_id" character varying(50) NOT NULL,
  "coupon_application_id" character varying(50) NOT NULL,
  PRIMARY KEY ("coupon_association_id", "coupon_application_id"),
  CONSTRAINT "coupon_association_coupon_applications_coupon_application_id" FOREIGN KEY ("coupon_application_id") REFERENCES "coupon_applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "coupon_association_coupon_applications_coupon_association_id" FOREIGN KEY ("coupon_association_id") REFERENCES "coupon_associations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "addons" table
CREATE TABLE "addons" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "lookup_key" character varying(255) NOT NULL,
  "name" character varying(255) NOT NULL,
  "description" text NULL,
  "metadata" jsonb NULL,
  PRIMARY KEY ("id")
);
-- Create index "addon_tenant_id_environment_id_lookup_key" to table: "addons"
CREATE UNIQUE INDEX "addon_tenant_id_environment_id_lookup_key" ON "addons" ("tenant_id", "environment_id", "lookup_key") WHERE (((status)::text = 'published'::text) AND (lookup_key IS NOT NULL) AND ((lookup_key)::text <> ''::text));
-- Create "plans" table
CREATE TABLE "plans" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "metadata" jsonb NULL,
  "lookup_key" character varying(255) NULL,
  "name" character varying(255) NOT NULL,
  "description" text NULL,
  "display_order" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);
-- Create index "idx_tenant_environment_lookup_key" to table: "plans"
CREATE UNIQUE INDEX "idx_tenant_environment_lookup_key" ON "plans" ("tenant_id", "environment_id", "lookup_key") WHERE (((status)::text = 'published'::text) AND (lookup_key IS NOT NULL) AND ((lookup_key)::text <> ''::text));
-- Create index "plan_tenant_id_environment_id" to table: "plans"
CREATE INDEX "plan_tenant_id_environment_id" ON "plans" ("tenant_id", "environment_id");
-- Create "credit_grants" table
CREATE TABLE "credit_grants" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "name" character varying(255) NOT NULL,
  "scope" character varying(50) NOT NULL,
  "credits" numeric(20,8) NOT NULL,
  "conversion_rate" numeric(10,5) NULL,
  "topup_conversion_rate" numeric(10,5) NULL,
  "cadence" character varying(50) NOT NULL,
  "period" character varying(50) NULL,
  "period_count" bigint NULL,
  "expiration_type" character varying(50) NOT NULL,
  "expiration_duration" bigint NULL,
  "expiration_duration_unit" character varying(50) NULL,
  "priority" bigint NULL,
  "metadata" jsonb NULL,
  "start_date" timestamptz NULL,
  "end_date" timestamptz NULL,
  "credit_grant_anchor" timestamptz NULL,
  "addon_id" character varying(50) NULL,
  "plan_id" character varying(50) NULL,
  "subscription_id" character varying(50) NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "credit_grants_addons_credit_grants" FOREIGN KEY ("addon_id") REFERENCES "addons" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "credit_grants_plans_credit_grants" FOREIGN KEY ("plan_id") REFERENCES "plans" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "credit_grants_subscriptions_credit_grants" FOREIGN KEY ("subscription_id") REFERENCES "subscriptions" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "creditgrant_tenant_id_environment_id_status" to table: "credit_grants"
CREATE INDEX "creditgrant_tenant_id_environment_id_status" ON "credit_grants" ("tenant_id", "environment_id", "status");
-- Create index "idx_addon_id_not_null" to table: "credit_grants"
CREATE INDEX "idx_addon_id_not_null" ON "credit_grants" ("tenant_id", "environment_id", "scope", "addon_id") WHERE (addon_id IS NOT NULL);
-- Create index "idx_plan_id_not_null" to table: "credit_grants"
CREATE INDEX "idx_plan_id_not_null" ON "credit_grants" ("tenant_id", "environment_id", "scope", "plan_id") WHERE (plan_id IS NOT NULL);
-- Create index "idx_subscription_id_not_null" to table: "credit_grants"
CREATE INDEX "idx_subscription_id_not_null" ON "credit_grants" ("tenant_id", "environment_id", "scope", "subscription_id") WHERE (subscription_id IS NOT NULL);
-- Create "credit_notes" table
CREATE TABLE "credit_notes" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "invoice_id" character varying(50) NOT NULL,
  "customer_id" character varying(50) NOT NULL,
  "subscription_id" character varying(50) NULL,
  "credit_note_number" character varying(50) NOT NULL,
  "credit_note_status" character varying(50) NOT NULL DEFAULT 'DRAFT',
  "credit_note_type" character varying(50) NOT NULL,
  "refund_status" character varying(50) NULL,
  "reason" character varying(50) NOT NULL,
  "memo" text NOT NULL,
  "currency" character varying(50) NOT NULL,
  "idempotency_key" character varying(100) NULL,
  "voided_at" timestamptz NULL,
  "finalized_at" timestamptz NULL,
  "metadata" jsonb NULL,
  "total_amount" numeric(20,8) NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "creditnote_tenant_id_environment_id_credit_note_status" to table: "credit_notes"
CREATE INDEX "creditnote_tenant_id_environment_id_credit_note_status" ON "credit_notes" ("tenant_id", "environment_id", "credit_note_status");
-- Create index "creditnote_tenant_id_environment_id_credit_note_type" to table: "credit_notes"
CREATE INDEX "creditnote_tenant_id_environment_id_credit_note_type" ON "credit_notes" ("tenant_id", "environment_id", "credit_note_type");
-- Create index "creditnote_tenant_id_environment_id_customer_id" to table: "credit_notes"
CREATE INDEX "creditnote_tenant_id_environment_id_customer_id" ON "credit_notes" ("tenant_id", "environment_id", "customer_id");
-- Create index "creditnote_tenant_id_environment_id_idempotency_key" to table: "credit_notes"
CREATE INDEX "creditnote_tenant_id_environment_id_idempotency_key" ON "credit_notes" ("tenant_id", "environment_id", "idempotency_key") WHERE ((idempotency_key IS NOT NULL) AND ((idempotency_key)::text <> ''::text));
-- Create index "creditnote_tenant_id_environment_id_invoice_id" to table: "credit_notes"
CREATE INDEX "creditnote_tenant_id_environment_id_invoice_id" ON "credit_notes" ("tenant_id", "environment_id", "invoice_id");
-- Create index "creditnote_tenant_id_environment_id_subscription_id" to table: "credit_notes"
CREATE INDEX "creditnote_tenant_id_environment_id_subscription_id" ON "credit_notes" ("tenant_id", "environment_id", "subscription_id");
-- Create index "idx_tenant_environment_credit_note_number_unique" to table: "credit_notes"
CREATE UNIQUE INDEX "idx_tenant_environment_credit_note_number_unique" ON "credit_notes" ("tenant_id", "environment_id", "credit_note_number") WHERE ((credit_note_number IS NOT NULL) AND ((credit_note_number)::text <> ''::text) AND ((status)::text = 'published'::text));
-- Create "credit_note_line_items" table
CREATE TABLE "credit_note_line_items" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "invoice_line_item_id" character varying(50) NOT NULL,
  "display_name" character varying NOT NULL,
  "amount" numeric(20,8) NOT NULL,
  "currency" character varying(10) NOT NULL,
  "metadata" jsonb NULL,
  "credit_note_id" character varying(50) NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "credit_note_line_items_credit_notes_line_items" FOREIGN KEY ("credit_note_id") REFERENCES "credit_notes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "entitlements" table
CREATE TABLE "entitlements" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "entity_type" character varying(50) NULL DEFAULT 'PLAN',
  "entity_id" character varying(50) NULL,
  "feature_id" character varying(50) NOT NULL,
  "feature_type" character varying(50) NOT NULL,
  "is_enabled" boolean NOT NULL DEFAULT false,
  "usage_limit" bigint NULL,
  "usage_reset_period" character varying(20) NULL,
  "is_soft_limit" boolean NOT NULL DEFAULT false,
  "static_value" character varying NULL,
  "display_order" bigint NOT NULL DEFAULT 0,
  "parent_entitlement_id" character varying(50) NULL,
  "start_date" timestamptz NULL,
  "end_date" timestamptz NULL,
  "config_value" jsonb NULL,
  "addon_entitlements" character varying(50) NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "entitlements_addons_entitlements" FOREIGN KEY ("addon_entitlements") REFERENCES "addons" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "entitlement_entity_id_entity_type_feature_id_start_date_end_dat" to table: "entitlements"
CREATE INDEX "entitlement_entity_id_entity_type_feature_id_start_date_end_dat" ON "entitlements" ("entity_id", "entity_type", "feature_id", "start_date", "end_date") WHERE (((entity_type)::text = 'SUBSCRIPTION'::text) AND ((status)::text = 'published'::text));
-- Create index "entitlement_tenant_id_environment_id_entity_type_entity_id" to table: "entitlements"
CREATE INDEX "entitlement_tenant_id_environment_id_entity_type_entity_id" ON "entitlements" ("tenant_id", "environment_id", "entity_type", "entity_id");
-- Create index "entitlement_tenant_id_environment_id_entity_type_entity_id_feat" to table: "entitlements"
CREATE UNIQUE INDEX "entitlement_tenant_id_environment_id_entity_type_entity_id_feat" ON "entitlements" ("tenant_id", "environment_id", "entity_type", "entity_id", "feature_id") WHERE ((status)::text = 'published'::text);
-- Create index "entitlement_tenant_id_environment_id_feature_id" to table: "entitlements"
CREATE INDEX "entitlement_tenant_id_environment_id_feature_id" ON "entitlements" ("tenant_id", "environment_id", "feature_id");
-- Create index "entitlement_tenant_id_environment_id_parent_entitlement_id" to table: "entitlements"
CREATE INDEX "entitlement_tenant_id_environment_id_parent_entitlement_id" ON "entitlements" ("tenant_id", "environment_id", "parent_entitlement_id");
-- Create "payments" table
CREATE TABLE "payments" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "idempotency_key" character varying(50) NOT NULL,
  "destination_type" character varying(50) NOT NULL,
  "destination_id" character varying(50) NOT NULL,
  "payment_method_type" character varying(50) NOT NULL,
  "payment_method_id" character varying(50) NULL,
  "payment_gateway" character varying(50) NULL,
  "gateway_payment_id" character varying(255) NULL,
  "gateway_tracking_id" character varying(255) NULL,
  "gateway_metadata" jsonb NULL,
  "amount" numeric(20,8) NOT NULL,
  "currency" character varying(10) NOT NULL,
  "payment_status" character varying(50) NOT NULL,
  "track_attempts" boolean NOT NULL DEFAULT false,
  "metadata" jsonb NULL,
  "succeeded_at" timestamptz NULL,
  "failed_at" timestamptz NULL,
  "refunded_at" timestamptz NULL,
  "voided_at" timestamptz NULL,
  "recorded_at" timestamptz NULL,
  "error_message" text NULL,
  PRIMARY KEY ("id")
);
-- Create index "idx_tenant_destination_status" to table: "payments"
CREATE INDEX "idx_tenant_destination_status" ON "payments" ("tenant_id", "environment_id", "destination_type", "destination_id", "payment_status", "status");
-- Create index "idx_tenant_gateway_payment" to table: "payments"
CREATE INDEX "idx_tenant_gateway_payment" ON "payments" ("tenant_id", "environment_id", "payment_gateway", "gateway_payment_id") WHERE ((payment_gateway IS NOT NULL) AND (gateway_payment_id IS NOT NULL));
-- Create index "idx_tenant_payment_method_status" to table: "payments"
CREATE INDEX "idx_tenant_payment_method_status" ON "payments" ("tenant_id", "environment_id", "payment_method_type", "payment_method_id", "payment_status", "status");
-- Create index "payments_idempotency_key_key" to table: "payments"
CREATE UNIQUE INDEX "payments_idempotency_key_key" ON "payments" ("idempotency_key");
-- Create "payment_attempts" table
CREATE TABLE "payment_attempts" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "payment_status" character varying(20) NOT NULL,
  "attempt_number" integer NOT NULL DEFAULT 1,
  "gateway_attempt_id" character varying(255) NULL,
  "error_message" text NULL,
  "metadata" jsonb NULL,
  "payment_id" character varying(50) NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "payment_attempts_payments_attempts" FOREIGN KEY ("payment_id") REFERENCES "payments" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "idx_gateway_attempt" to table: "payment_attempts"
CREATE INDEX "idx_gateway_attempt" ON "payment_attempts" ("gateway_attempt_id") WHERE (gateway_attempt_id IS NOT NULL);
-- Create index "idx_payment_attempt_number_unique" to table: "payment_attempts"
CREATE UNIQUE INDEX "idx_payment_attempt_number_unique" ON "payment_attempts" ("payment_id", "attempt_number");
-- Create index "idx_payment_attempt_status" to table: "payment_attempts"
CREATE INDEX "idx_payment_attempt_status" ON "payment_attempts" ("payment_id", "status");
-- Create "subscription_pauses" table
CREATE TABLE "subscription_pauses" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "pause_status" character varying(50) NOT NULL,
  "pause_mode" character varying(50) NOT NULL DEFAULT 'scheduled',
  "resume_mode" character varying(50) NULL,
  "pause_start" timestamptz NOT NULL,
  "pause_end" timestamptz NULL,
  "resumed_at" timestamptz NULL,
  "original_period_start" timestamptz NOT NULL,
  "original_period_end" timestamptz NOT NULL,
  "reason" text NULL,
  "metadata" jsonb NULL,
  "subscription_id" character varying(50) NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "subscription_pauses_subscriptions_pauses" FOREIGN KEY ("subscription_id") REFERENCES "subscriptions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "subscriptionpause_tenant_id_environment_id_pause_end_status" to table: "subscription_pauses"
CREATE INDEX "subscriptionpause_tenant_id_environment_id_pause_end_status" ON "subscription_pauses" ("tenant_id", "environment_id", "pause_end", "status");
-- Create index "subscriptionpause_tenant_id_environment_id_pause_start_status" to table: "subscription_pauses"
CREATE INDEX "subscriptionpause_tenant_id_environment_id_pause_start_status" ON "subscription_pauses" ("tenant_id", "environment_id", "pause_start", "status");
-- Create index "subscriptionpause_tenant_id_environment_id_subscription_id_stat" to table: "subscription_pauses"
CREATE INDEX "subscriptionpause_tenant_id_environment_id_subscription_id_stat" ON "subscription_pauses" ("tenant_id", "environment_id", "subscription_id", "status");
-- Create "subscription_phases" table
CREATE TABLE "subscription_phases" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "metadata" jsonb NULL,
  "start_date" timestamptz NOT NULL,
  "end_date" timestamptz NULL,
  "subscription_id" character varying(50) NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "subscription_phases_subscriptions_phases" FOREIGN KEY ("subscription_id") REFERENCES "subscriptions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "subscriptionphase_tenant_id_environment_id" to table: "subscription_phases"
CREATE INDEX "subscriptionphase_tenant_id_environment_id" ON "subscription_phases" ("tenant_id", "environment_id");
-- Create "subscription_schedules" table
CREATE TABLE "subscription_schedules" (
  "id" character varying(50) NOT NULL,
  "tenant_id" character varying(50) NOT NULL,
  "status" character varying(20) NOT NULL DEFAULT 'published',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "created_by" character varying NULL,
  "updated_by" character varying NULL,
  "environment_id" character varying(50) NULL DEFAULT '',
  "metadata" jsonb NULL,
  "schedule_type" character varying(50) NOT NULL,
  "scheduled_at" timestamptz NOT NULL,
  "configuration" jsonb NOT NULL,
  "executed_at" timestamptz NULL,
  "cancelled_at" timestamptz NULL,
  "execution_result" jsonb NULL,
  "error_message" text NULL,
  "subscription_id" character varying(50) NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "subscription_schedules_subscriptions_schedules" FOREIGN KEY ("subscription_id") REFERENCES "subscriptions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "subscriptionschedule_scheduled_at_status" to table: "subscription_schedules"
CREATE INDEX "subscriptionschedule_scheduled_at_status" ON "subscription_schedules" ("scheduled_at", "status") WHERE ((status)::text = 'pending'::text);
-- Create index "subscriptionschedule_status_schedule_type" to table: "subscription_schedules"
CREATE INDEX "subscriptionschedule_status_schedule_type" ON "subscription_schedules" ("status", "schedule_type") WHERE ((status)::text = 'pending'::text);
-- Create index "subscriptionschedule_subscription_id" to table: "subscription_schedules"
CREATE INDEX "subscriptionschedule_subscription_id" ON "subscription_schedules" ("subscription_id");
-- Create index "subscriptionschedule_subscription_id_schedule_type" to table: "subscription_schedules"
CREATE UNIQUE INDEX "subscriptionschedule_subscription_id_schedule_type" ON "subscription_schedules" ("subscription_id", "schedule_type") WHERE ((status)::text = 'pending'::text);
-- Create index "subscriptionschedule_tenant_id_environment_id" to table: "subscription_schedules"
CREATE INDEX "subscriptionschedule_tenant_id_environment_id" ON "subscription_schedules" ("tenant_id", "environment_id");
