# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/benefit_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16v1/benefit_event.proto\x12\nbenefitsv1\"\xe6\x03\n\x0c\x42\x65nefitEvent\x12\x19\n\x08\x65vent_id\x18\x01 \x01(\tR\x07\x65ventId\x12\x1a\n\x08username\x18\x02 \x01(\tR\x08username\x12,\n\x0fsubscription_id\x18\x03 \x01(\tH\x00R\x0esubscriptionId\x88\x01\x01\x12\"\n\nfeature_id\x18\x04 \x01(\tH\x01R\tfeatureId\x88\x01\x01\x12\x1f\n\x08\x63\x61tegory\x18\x05 \x01(\tH\x02R\x08\x63\x61tegory\x88\x01\x01\x12\x14\n\x05value\x18\x06 \x01(\x03R\x05value\x12\x1c\n\ttimestamp\x18\x07 \x01(\x03R\ttimestamp\x12&\n\x0c\x62\x65nefit_type\x18\x08 \x01(\tH\x03R\x0b\x62\x65nefitType\x88\x01\x01\x12\x39\n\nentry_type\x18\t \x01(\x0e\x32\x15.benefitsv1.EntryTypeH\x04R\tentryType\x88\x01\x01\x12/\n\x11original_event_id\x18\n \x01(\tH\x05R\x0foriginalEventId\x88\x01\x01\x42\x12\n\x10_subscription_idB\r\n\x0b_feature_idB\x0b\n\t_categoryB\x0f\n\r_benefit_typeB\r\n\x0b_entry_typeB\x14\n\x12_original_event_id*@\n\tEntryType\x12\x1a\n\x16\x45NTRY_TYPE_UNSPECIFIED\x10\x00\x12\t\n\x05GRANT\x10\x01\x12\x0c\n\x08REVERSAL\x10\x02\x42<Z:gitlab.famapp.in/backend/flexprice/protos/pb/v1;benefitsv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.benefit_event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z:gitlab.famapp.in/backend/flexprice/protos/pb/v1;benefitsv1'
  _globals['_ENTRYTYPE']._serialized_start=527
  _globals['_ENTRYTYPE']._serialized_end=591
  _globals['_BENEFITEVENT']._serialized_start=39
  _globals['_BENEFITEVENT']._serialized_end=525
# @@protoc_insertion_point(module_scope)
