# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/benefit_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16v1/benefit_event.proto\x12\nbenefitsv1\"\xdc\x01\n\x0c\x42\x65nefitEvent\x12\x19\n\x08\x65vent_id\x18\x01 \x01(\tR\x07\x65ventId\x12\'\n\x0fsubscription_id\x18\x02 \x01(\tR\x0esubscriptionId\x12\x19\n\x08\x63ycle_id\x18\x03 \x01(\tR\x07\x63ycleId\x12\x1d\n\nfeature_id\x18\x04 \x01(\tR\tfeatureId\x12\x1a\n\x08\x63\x61tegory\x18\x05 \x01(\tR\x08\x63\x61tegory\x12\x14\n\x05value\x18\x06 \x01(\x03R\x05value\x12\x1c\n\ttimestamp\x18\x07 \x01(\x03R\ttimestampB<Z:gitlab.famapp.in/backend/flexprice/protos/pb/v1;benefitsv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.benefit_event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z:gitlab.famapp.in/backend/flexprice/protos/pb/v1;benefitsv1'
  _globals['_BENEFITEVENT']._serialized_start=39
  _globals['_BENEFITEVENT']._serialized_end=259
# @@protoc_insertion_point(module_scope)
