// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/benefitledger"
)

// BenefitLedger is the model entity for the BenefitLedger schema.
type BenefitLedger struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy string `json:"updated_by,omitempty"`
	// EnvironmentID holds the value of the "environment_id" field.
	EnvironmentID string `json:"environment_id,omitempty"`
	// EventID holds the value of the "event_id" field.
	EventID string `json:"event_id,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID string `json:"subscription_id,omitempty"`
	// CustomerID holds the value of the "customer_id" field.
	CustomerID string `json:"customer_id,omitempty"`
	// Sku holds the value of the "sku" field.
	Sku string `json:"sku,omitempty"`
	// CycleID holds the value of the "cycle_id" field.
	CycleID string `json:"cycle_id,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// FeatureID holds the value of the "feature_id" field.
	FeatureID string `json:"feature_id,omitempty"`
	// Value holds the value of the "value" field.
	Value int `json:"value,omitempty"`
	// EventTimestamp holds the value of the "event_timestamp" field.
	EventTimestamp time.Time `json:"event_timestamp,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BenefitLedger) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case benefitledger.FieldValue:
			values[i] = new(sql.NullInt64)
		case benefitledger.FieldID, benefitledger.FieldTenantID, benefitledger.FieldStatus, benefitledger.FieldCreatedBy, benefitledger.FieldUpdatedBy, benefitledger.FieldEnvironmentID, benefitledger.FieldEventID, benefitledger.FieldSubscriptionID, benefitledger.FieldCustomerID, benefitledger.FieldSku, benefitledger.FieldCycleID, benefitledger.FieldCategory, benefitledger.FieldFeatureID:
			values[i] = new(sql.NullString)
		case benefitledger.FieldCreatedAt, benefitledger.FieldUpdatedAt, benefitledger.FieldEventTimestamp:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BenefitLedger fields.
func (bl *BenefitLedger) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case benefitledger.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				bl.ID = value.String
			}
		case benefitledger.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				bl.TenantID = value.String
			}
		case benefitledger.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				bl.Status = value.String
			}
		case benefitledger.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				bl.CreatedAt = value.Time
			}
		case benefitledger.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				bl.UpdatedAt = value.Time
			}
		case benefitledger.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				bl.CreatedBy = value.String
			}
		case benefitledger.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				bl.UpdatedBy = value.String
			}
		case benefitledger.FieldEnvironmentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field environment_id", values[i])
			} else if value.Valid {
				bl.EnvironmentID = value.String
			}
		case benefitledger.FieldEventID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_id", values[i])
			} else if value.Valid {
				bl.EventID = value.String
			}
		case benefitledger.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				bl.SubscriptionID = value.String
			}
		case benefitledger.FieldCustomerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_id", values[i])
			} else if value.Valid {
				bl.CustomerID = value.String
			}
		case benefitledger.FieldSku:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sku", values[i])
			} else if value.Valid {
				bl.Sku = value.String
			}
		case benefitledger.FieldCycleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cycle_id", values[i])
			} else if value.Valid {
				bl.CycleID = value.String
			}
		case benefitledger.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				bl.Category = value.String
			}
		case benefitledger.FieldFeatureID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field feature_id", values[i])
			} else if value.Valid {
				bl.FeatureID = value.String
			}
		case benefitledger.FieldValue:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				bl.Value = int(value.Int64)
			}
		case benefitledger.FieldEventTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field event_timestamp", values[i])
			} else if value.Valid {
				bl.EventTimestamp = value.Time
			}
		default:
			bl.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the BenefitLedger.
// This includes values selected through modifiers, order, etc.
func (bl *BenefitLedger) GetValue(name string) (ent.Value, error) {
	return bl.selectValues.Get(name)
}

// Update returns a builder for updating this BenefitLedger.
// Note that you need to call BenefitLedger.Unwrap() before calling this method if this BenefitLedger
// was returned from a transaction, and the transaction was committed or rolled back.
func (bl *BenefitLedger) Update() *BenefitLedgerUpdateOne {
	return NewBenefitLedgerClient(bl.config).UpdateOne(bl)
}

// Unwrap unwraps the BenefitLedger entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (bl *BenefitLedger) Unwrap() *BenefitLedger {
	_tx, ok := bl.config.driver.(*txDriver)
	if !ok {
		panic("ent: BenefitLedger is not a transactional entity")
	}
	bl.config.driver = _tx.drv
	return bl
}

// String implements the fmt.Stringer.
func (bl *BenefitLedger) String() string {
	var builder strings.Builder
	builder.WriteString("BenefitLedger(")
	builder.WriteString(fmt.Sprintf("id=%v, ", bl.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(bl.TenantID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(bl.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(bl.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(bl.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(bl.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(bl.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("environment_id=")
	builder.WriteString(bl.EnvironmentID)
	builder.WriteString(", ")
	builder.WriteString("event_id=")
	builder.WriteString(bl.EventID)
	builder.WriteString(", ")
	builder.WriteString("subscription_id=")
	builder.WriteString(bl.SubscriptionID)
	builder.WriteString(", ")
	builder.WriteString("customer_id=")
	builder.WriteString(bl.CustomerID)
	builder.WriteString(", ")
	builder.WriteString("sku=")
	builder.WriteString(bl.Sku)
	builder.WriteString(", ")
	builder.WriteString("cycle_id=")
	builder.WriteString(bl.CycleID)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(bl.Category)
	builder.WriteString(", ")
	builder.WriteString("feature_id=")
	builder.WriteString(bl.FeatureID)
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(fmt.Sprintf("%v", bl.Value))
	builder.WriteString(", ")
	builder.WriteString("event_timestamp=")
	builder.WriteString(bl.EventTimestamp.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BenefitLedgers is a parsable slice of BenefitLedger.
type BenefitLedgers []*BenefitLedger
