// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/benefitledger"
)

// BenefitLedgerCreate is the builder for creating a BenefitLedger entity.
type BenefitLedgerCreate struct {
	config
	mutation *BenefitLedgerMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (blc *BenefitLedgerCreate) SetTenantID(s string) *BenefitLedgerCreate {
	blc.mutation.SetTenantID(s)
	return blc
}

// SetStatus sets the "status" field.
func (blc *BenefitLedgerCreate) SetStatus(s string) *BenefitLedgerCreate {
	blc.mutation.SetStatus(s)
	return blc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (blc *BenefitLedgerCreate) SetNillableStatus(s *string) *BenefitLedgerCreate {
	if s != nil {
		blc.SetStatus(*s)
	}
	return blc
}

// SetCreatedAt sets the "created_at" field.
func (blc *BenefitLedgerCreate) SetCreatedAt(t time.Time) *BenefitLedgerCreate {
	blc.mutation.SetCreatedAt(t)
	return blc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (blc *BenefitLedgerCreate) SetNillableCreatedAt(t *time.Time) *BenefitLedgerCreate {
	if t != nil {
		blc.SetCreatedAt(*t)
	}
	return blc
}

// SetUpdatedAt sets the "updated_at" field.
func (blc *BenefitLedgerCreate) SetUpdatedAt(t time.Time) *BenefitLedgerCreate {
	blc.mutation.SetUpdatedAt(t)
	return blc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (blc *BenefitLedgerCreate) SetNillableUpdatedAt(t *time.Time) *BenefitLedgerCreate {
	if t != nil {
		blc.SetUpdatedAt(*t)
	}
	return blc
}

// SetCreatedBy sets the "created_by" field.
func (blc *BenefitLedgerCreate) SetCreatedBy(s string) *BenefitLedgerCreate {
	blc.mutation.SetCreatedBy(s)
	return blc
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (blc *BenefitLedgerCreate) SetNillableCreatedBy(s *string) *BenefitLedgerCreate {
	if s != nil {
		blc.SetCreatedBy(*s)
	}
	return blc
}

// SetUpdatedBy sets the "updated_by" field.
func (blc *BenefitLedgerCreate) SetUpdatedBy(s string) *BenefitLedgerCreate {
	blc.mutation.SetUpdatedBy(s)
	return blc
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (blc *BenefitLedgerCreate) SetNillableUpdatedBy(s *string) *BenefitLedgerCreate {
	if s != nil {
		blc.SetUpdatedBy(*s)
	}
	return blc
}

// SetEnvironmentID sets the "environment_id" field.
func (blc *BenefitLedgerCreate) SetEnvironmentID(s string) *BenefitLedgerCreate {
	blc.mutation.SetEnvironmentID(s)
	return blc
}

// SetNillableEnvironmentID sets the "environment_id" field if the given value is not nil.
func (blc *BenefitLedgerCreate) SetNillableEnvironmentID(s *string) *BenefitLedgerCreate {
	if s != nil {
		blc.SetEnvironmentID(*s)
	}
	return blc
}

// SetEventID sets the "event_id" field.
func (blc *BenefitLedgerCreate) SetEventID(s string) *BenefitLedgerCreate {
	blc.mutation.SetEventID(s)
	return blc
}

// SetSubscriptionID sets the "subscription_id" field.
func (blc *BenefitLedgerCreate) SetSubscriptionID(s string) *BenefitLedgerCreate {
	blc.mutation.SetSubscriptionID(s)
	return blc
}

// SetCustomerID sets the "customer_id" field.
func (blc *BenefitLedgerCreate) SetCustomerID(s string) *BenefitLedgerCreate {
	blc.mutation.SetCustomerID(s)
	return blc
}

// SetProduct sets the "product" field.
func (blc *BenefitLedgerCreate) SetProduct(s string) *BenefitLedgerCreate {
	blc.mutation.SetProduct(s)
	return blc
}

// SetCycleID sets the "cycle_id" field.
func (blc *BenefitLedgerCreate) SetCycleID(s string) *BenefitLedgerCreate {
	blc.mutation.SetCycleID(s)
	return blc
}

// SetCategory sets the "category" field.
func (blc *BenefitLedgerCreate) SetCategory(s string) *BenefitLedgerCreate {
	blc.mutation.SetCategory(s)
	return blc
}

// SetFeatureID sets the "feature_id" field.
func (blc *BenefitLedgerCreate) SetFeatureID(s string) *BenefitLedgerCreate {
	blc.mutation.SetFeatureID(s)
	return blc
}

// SetNillableFeatureID sets the "feature_id" field if the given value is not nil.
func (blc *BenefitLedgerCreate) SetNillableFeatureID(s *string) *BenefitLedgerCreate {
	if s != nil {
		blc.SetFeatureID(*s)
	}
	return blc
}

// SetValue sets the "value" field.
func (blc *BenefitLedgerCreate) SetValue(i int) *BenefitLedgerCreate {
	blc.mutation.SetValue(i)
	return blc
}

// SetEventTimestamp sets the "event_timestamp" field.
func (blc *BenefitLedgerCreate) SetEventTimestamp(t time.Time) *BenefitLedgerCreate {
	blc.mutation.SetEventTimestamp(t)
	return blc
}

// SetID sets the "id" field.
func (blc *BenefitLedgerCreate) SetID(s string) *BenefitLedgerCreate {
	blc.mutation.SetID(s)
	return blc
}

// Mutation returns the BenefitLedgerMutation object of the builder.
func (blc *BenefitLedgerCreate) Mutation() *BenefitLedgerMutation {
	return blc.mutation
}

// Save creates the BenefitLedger in the database.
func (blc *BenefitLedgerCreate) Save(ctx context.Context) (*BenefitLedger, error) {
	blc.defaults()
	return withHooks(ctx, blc.sqlSave, blc.mutation, blc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (blc *BenefitLedgerCreate) SaveX(ctx context.Context) *BenefitLedger {
	v, err := blc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (blc *BenefitLedgerCreate) Exec(ctx context.Context) error {
	_, err := blc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (blc *BenefitLedgerCreate) ExecX(ctx context.Context) {
	if err := blc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (blc *BenefitLedgerCreate) defaults() {
	if _, ok := blc.mutation.Status(); !ok {
		v := benefitledger.DefaultStatus
		blc.mutation.SetStatus(v)
	}
	if _, ok := blc.mutation.CreatedAt(); !ok {
		v := benefitledger.DefaultCreatedAt()
		blc.mutation.SetCreatedAt(v)
	}
	if _, ok := blc.mutation.UpdatedAt(); !ok {
		v := benefitledger.DefaultUpdatedAt()
		blc.mutation.SetUpdatedAt(v)
	}
	if _, ok := blc.mutation.EnvironmentID(); !ok {
		v := benefitledger.DefaultEnvironmentID
		blc.mutation.SetEnvironmentID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (blc *BenefitLedgerCreate) check() error {
	if _, ok := blc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "BenefitLedger.tenant_id"`)}
	}
	if v, ok := blc.mutation.TenantID(); ok {
		if err := benefitledger.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "BenefitLedger.tenant_id": %w`, err)}
		}
	}
	if _, ok := blc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "BenefitLedger.status"`)}
	}
	if _, ok := blc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BenefitLedger.created_at"`)}
	}
	if _, ok := blc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BenefitLedger.updated_at"`)}
	}
	if _, ok := blc.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "BenefitLedger.event_id"`)}
	}
	if v, ok := blc.mutation.EventID(); ok {
		if err := benefitledger.EventIDValidator(v); err != nil {
			return &ValidationError{Name: "event_id", err: fmt.Errorf(`ent: validator failed for field "BenefitLedger.event_id": %w`, err)}
		}
	}
	if _, ok := blc.mutation.SubscriptionID(); !ok {
		return &ValidationError{Name: "subscription_id", err: errors.New(`ent: missing required field "BenefitLedger.subscription_id"`)}
	}
	if v, ok := blc.mutation.SubscriptionID(); ok {
		if err := benefitledger.SubscriptionIDValidator(v); err != nil {
			return &ValidationError{Name: "subscription_id", err: fmt.Errorf(`ent: validator failed for field "BenefitLedger.subscription_id": %w`, err)}
		}
	}
	if _, ok := blc.mutation.CustomerID(); !ok {
		return &ValidationError{Name: "customer_id", err: errors.New(`ent: missing required field "BenefitLedger.customer_id"`)}
	}
	if v, ok := blc.mutation.CustomerID(); ok {
		if err := benefitledger.CustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "customer_id", err: fmt.Errorf(`ent: validator failed for field "BenefitLedger.customer_id": %w`, err)}
		}
	}
	if _, ok := blc.mutation.Product(); !ok {
		return &ValidationError{Name: "product", err: errors.New(`ent: missing required field "BenefitLedger.product"`)}
	}
	if v, ok := blc.mutation.Product(); ok {
		if err := benefitledger.ProductValidator(v); err != nil {
			return &ValidationError{Name: "product", err: fmt.Errorf(`ent: validator failed for field "BenefitLedger.product": %w`, err)}
		}
	}
	if _, ok := blc.mutation.CycleID(); !ok {
		return &ValidationError{Name: "cycle_id", err: errors.New(`ent: missing required field "BenefitLedger.cycle_id"`)}
	}
	if v, ok := blc.mutation.CycleID(); ok {
		if err := benefitledger.CycleIDValidator(v); err != nil {
			return &ValidationError{Name: "cycle_id", err: fmt.Errorf(`ent: validator failed for field "BenefitLedger.cycle_id": %w`, err)}
		}
	}
	if _, ok := blc.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "BenefitLedger.category"`)}
	}
	if _, ok := blc.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "BenefitLedger.value"`)}
	}
	if _, ok := blc.mutation.EventTimestamp(); !ok {
		return &ValidationError{Name: "event_timestamp", err: errors.New(`ent: missing required field "BenefitLedger.event_timestamp"`)}
	}
	return nil
}

func (blc *BenefitLedgerCreate) sqlSave(ctx context.Context) (*BenefitLedger, error) {
	if err := blc.check(); err != nil {
		return nil, err
	}
	_node, _spec := blc.createSpec()
	if err := sqlgraph.CreateNode(ctx, blc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected BenefitLedger.ID type: %T", _spec.ID.Value)
		}
	}
	blc.mutation.id = &_node.ID
	blc.mutation.done = true
	return _node, nil
}

func (blc *BenefitLedgerCreate) createSpec() (*BenefitLedger, *sqlgraph.CreateSpec) {
	var (
		_node = &BenefitLedger{config: blc.config}
		_spec = sqlgraph.NewCreateSpec(benefitledger.Table, sqlgraph.NewFieldSpec(benefitledger.FieldID, field.TypeString))
	)
	if id, ok := blc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := blc.mutation.TenantID(); ok {
		_spec.SetField(benefitledger.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := blc.mutation.Status(); ok {
		_spec.SetField(benefitledger.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := blc.mutation.CreatedAt(); ok {
		_spec.SetField(benefitledger.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := blc.mutation.UpdatedAt(); ok {
		_spec.SetField(benefitledger.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := blc.mutation.CreatedBy(); ok {
		_spec.SetField(benefitledger.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := blc.mutation.UpdatedBy(); ok {
		_spec.SetField(benefitledger.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := blc.mutation.EnvironmentID(); ok {
		_spec.SetField(benefitledger.FieldEnvironmentID, field.TypeString, value)
		_node.EnvironmentID = value
	}
	if value, ok := blc.mutation.EventID(); ok {
		_spec.SetField(benefitledger.FieldEventID, field.TypeString, value)
		_node.EventID = value
	}
	if value, ok := blc.mutation.SubscriptionID(); ok {
		_spec.SetField(benefitledger.FieldSubscriptionID, field.TypeString, value)
		_node.SubscriptionID = value
	}
	if value, ok := blc.mutation.CustomerID(); ok {
		_spec.SetField(benefitledger.FieldCustomerID, field.TypeString, value)
		_node.CustomerID = value
	}
	if value, ok := blc.mutation.Product(); ok {
		_spec.SetField(benefitledger.FieldProduct, field.TypeString, value)
		_node.Product = value
	}
	if value, ok := blc.mutation.CycleID(); ok {
		_spec.SetField(benefitledger.FieldCycleID, field.TypeString, value)
		_node.CycleID = value
	}
	if value, ok := blc.mutation.Category(); ok {
		_spec.SetField(benefitledger.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := blc.mutation.FeatureID(); ok {
		_spec.SetField(benefitledger.FieldFeatureID, field.TypeString, value)
		_node.FeatureID = value
	}
	if value, ok := blc.mutation.Value(); ok {
		_spec.SetField(benefitledger.FieldValue, field.TypeInt, value)
		_node.Value = value
	}
	if value, ok := blc.mutation.EventTimestamp(); ok {
		_spec.SetField(benefitledger.FieldEventTimestamp, field.TypeTime, value)
		_node.EventTimestamp = value
	}
	return _node, _spec
}

// BenefitLedgerCreateBulk is the builder for creating many BenefitLedger entities in bulk.
type BenefitLedgerCreateBulk struct {
	config
	err      error
	builders []*BenefitLedgerCreate
}

// Save creates the BenefitLedger entities in the database.
func (blcb *BenefitLedgerCreateBulk) Save(ctx context.Context) ([]*BenefitLedger, error) {
	if blcb.err != nil {
		return nil, blcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(blcb.builders))
	nodes := make([]*BenefitLedger, len(blcb.builders))
	mutators := make([]Mutator, len(blcb.builders))
	for i := range blcb.builders {
		func(i int, root context.Context) {
			builder := blcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BenefitLedgerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, blcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, blcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, blcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (blcb *BenefitLedgerCreateBulk) SaveX(ctx context.Context) []*BenefitLedger {
	v, err := blcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (blcb *BenefitLedgerCreateBulk) Exec(ctx context.Context) error {
	_, err := blcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (blcb *BenefitLedgerCreateBulk) ExecX(ctx context.Context) {
	if err := blcb.Exec(ctx); err != nil {
		panic(err)
	}
}
