// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/benefitledger"
	"github.com/flexprice/flexprice/ent/predicate"
)

// BenefitLedgerQuery is the builder for querying BenefitLedger entities.
type BenefitLedgerQuery struct {
	config
	ctx        *QueryContext
	order      []benefitledger.OrderOption
	inters     []Interceptor
	predicates []predicate.BenefitLedger
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BenefitLedgerQuery builder.
func (blq *BenefitLedgerQuery) Where(ps ...predicate.BenefitLedger) *BenefitLedgerQuery {
	blq.predicates = append(blq.predicates, ps...)
	return blq
}

// Limit the number of records to be returned by this query.
func (blq *BenefitLedgerQuery) Limit(limit int) *BenefitLedgerQuery {
	blq.ctx.Limit = &limit
	return blq
}

// Offset to start from.
func (blq *BenefitLedgerQuery) Offset(offset int) *BenefitLedgerQuery {
	blq.ctx.Offset = &offset
	return blq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (blq *BenefitLedgerQuery) Unique(unique bool) *BenefitLedgerQuery {
	blq.ctx.Unique = &unique
	return blq
}

// Order specifies how the records should be ordered.
func (blq *BenefitLedgerQuery) Order(o ...benefitledger.OrderOption) *BenefitLedgerQuery {
	blq.order = append(blq.order, o...)
	return blq
}

// First returns the first BenefitLedger entity from the query.
// Returns a *NotFoundError when no BenefitLedger was found.
func (blq *BenefitLedgerQuery) First(ctx context.Context) (*BenefitLedger, error) {
	nodes, err := blq.Limit(1).All(setContextOp(ctx, blq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{benefitledger.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (blq *BenefitLedgerQuery) FirstX(ctx context.Context) *BenefitLedger {
	node, err := blq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BenefitLedger ID from the query.
// Returns a *NotFoundError when no BenefitLedger ID was found.
func (blq *BenefitLedgerQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = blq.Limit(1).IDs(setContextOp(ctx, blq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{benefitledger.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (blq *BenefitLedgerQuery) FirstIDX(ctx context.Context) string {
	id, err := blq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BenefitLedger entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BenefitLedger entity is found.
// Returns a *NotFoundError when no BenefitLedger entities are found.
func (blq *BenefitLedgerQuery) Only(ctx context.Context) (*BenefitLedger, error) {
	nodes, err := blq.Limit(2).All(setContextOp(ctx, blq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{benefitledger.Label}
	default:
		return nil, &NotSingularError{benefitledger.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (blq *BenefitLedgerQuery) OnlyX(ctx context.Context) *BenefitLedger {
	node, err := blq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BenefitLedger ID in the query.
// Returns a *NotSingularError when more than one BenefitLedger ID is found.
// Returns a *NotFoundError when no entities are found.
func (blq *BenefitLedgerQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = blq.Limit(2).IDs(setContextOp(ctx, blq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{benefitledger.Label}
	default:
		err = &NotSingularError{benefitledger.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (blq *BenefitLedgerQuery) OnlyIDX(ctx context.Context) string {
	id, err := blq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BenefitLedgers.
func (blq *BenefitLedgerQuery) All(ctx context.Context) ([]*BenefitLedger, error) {
	ctx = setContextOp(ctx, blq.ctx, ent.OpQueryAll)
	if err := blq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BenefitLedger, *BenefitLedgerQuery]()
	return withInterceptors[[]*BenefitLedger](ctx, blq, qr, blq.inters)
}

// AllX is like All, but panics if an error occurs.
func (blq *BenefitLedgerQuery) AllX(ctx context.Context) []*BenefitLedger {
	nodes, err := blq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BenefitLedger IDs.
func (blq *BenefitLedgerQuery) IDs(ctx context.Context) (ids []string, err error) {
	if blq.ctx.Unique == nil && blq.path != nil {
		blq.Unique(true)
	}
	ctx = setContextOp(ctx, blq.ctx, ent.OpQueryIDs)
	if err = blq.Select(benefitledger.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (blq *BenefitLedgerQuery) IDsX(ctx context.Context) []string {
	ids, err := blq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (blq *BenefitLedgerQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, blq.ctx, ent.OpQueryCount)
	if err := blq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, blq, querierCount[*BenefitLedgerQuery](), blq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (blq *BenefitLedgerQuery) CountX(ctx context.Context) int {
	count, err := blq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (blq *BenefitLedgerQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, blq.ctx, ent.OpQueryExist)
	switch _, err := blq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (blq *BenefitLedgerQuery) ExistX(ctx context.Context) bool {
	exist, err := blq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BenefitLedgerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (blq *BenefitLedgerQuery) Clone() *BenefitLedgerQuery {
	if blq == nil {
		return nil
	}
	return &BenefitLedgerQuery{
		config:     blq.config,
		ctx:        blq.ctx.Clone(),
		order:      append([]benefitledger.OrderOption{}, blq.order...),
		inters:     append([]Interceptor{}, blq.inters...),
		predicates: append([]predicate.BenefitLedger{}, blq.predicates...),
		// clone intermediate query.
		sql:  blq.sql.Clone(),
		path: blq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BenefitLedger.Query().
//		GroupBy(benefitledger.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (blq *BenefitLedgerQuery) GroupBy(field string, fields ...string) *BenefitLedgerGroupBy {
	blq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BenefitLedgerGroupBy{build: blq}
	grbuild.flds = &blq.ctx.Fields
	grbuild.label = benefitledger.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//	}
//
//	client.BenefitLedger.Query().
//		Select(benefitledger.FieldTenantID).
//		Scan(ctx, &v)
func (blq *BenefitLedgerQuery) Select(fields ...string) *BenefitLedgerSelect {
	blq.ctx.Fields = append(blq.ctx.Fields, fields...)
	sbuild := &BenefitLedgerSelect{BenefitLedgerQuery: blq}
	sbuild.label = benefitledger.Label
	sbuild.flds, sbuild.scan = &blq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BenefitLedgerSelect configured with the given aggregations.
func (blq *BenefitLedgerQuery) Aggregate(fns ...AggregateFunc) *BenefitLedgerSelect {
	return blq.Select().Aggregate(fns...)
}

func (blq *BenefitLedgerQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range blq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, blq); err != nil {
				return err
			}
		}
	}
	for _, f := range blq.ctx.Fields {
		if !benefitledger.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if blq.path != nil {
		prev, err := blq.path(ctx)
		if err != nil {
			return err
		}
		blq.sql = prev
	}
	return nil
}

func (blq *BenefitLedgerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BenefitLedger, error) {
	var (
		nodes = []*BenefitLedger{}
		_spec = blq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BenefitLedger).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BenefitLedger{config: blq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, blq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (blq *BenefitLedgerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := blq.querySpec()
	_spec.Node.Columns = blq.ctx.Fields
	if len(blq.ctx.Fields) > 0 {
		_spec.Unique = blq.ctx.Unique != nil && *blq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, blq.driver, _spec)
}

func (blq *BenefitLedgerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(benefitledger.Table, benefitledger.Columns, sqlgraph.NewFieldSpec(benefitledger.FieldID, field.TypeString))
	_spec.From = blq.sql
	if unique := blq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if blq.path != nil {
		_spec.Unique = true
	}
	if fields := blq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, benefitledger.FieldID)
		for i := range fields {
			if fields[i] != benefitledger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := blq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := blq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := blq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := blq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (blq *BenefitLedgerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(blq.driver.Dialect())
	t1 := builder.Table(benefitledger.Table)
	columns := blq.ctx.Fields
	if len(columns) == 0 {
		columns = benefitledger.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if blq.sql != nil {
		selector = blq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if blq.ctx.Unique != nil && *blq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range blq.predicates {
		p(selector)
	}
	for _, p := range blq.order {
		p(selector)
	}
	if offset := blq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := blq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BenefitLedgerGroupBy is the group-by builder for BenefitLedger entities.
type BenefitLedgerGroupBy struct {
	selector
	build *BenefitLedgerQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (blgb *BenefitLedgerGroupBy) Aggregate(fns ...AggregateFunc) *BenefitLedgerGroupBy {
	blgb.fns = append(blgb.fns, fns...)
	return blgb
}

// Scan applies the selector query and scans the result into the given value.
func (blgb *BenefitLedgerGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, blgb.build.ctx, ent.OpQueryGroupBy)
	if err := blgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BenefitLedgerQuery, *BenefitLedgerGroupBy](ctx, blgb.build, blgb, blgb.build.inters, v)
}

func (blgb *BenefitLedgerGroupBy) sqlScan(ctx context.Context, root *BenefitLedgerQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(blgb.fns))
	for _, fn := range blgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*blgb.flds)+len(blgb.fns))
		for _, f := range *blgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*blgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := blgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BenefitLedgerSelect is the builder for selecting fields of BenefitLedger entities.
type BenefitLedgerSelect struct {
	*BenefitLedgerQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bls *BenefitLedgerSelect) Aggregate(fns ...AggregateFunc) *BenefitLedgerSelect {
	bls.fns = append(bls.fns, fns...)
	return bls
}

// Scan applies the selector query and scans the result into the given value.
func (bls *BenefitLedgerSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bls.ctx, ent.OpQuerySelect)
	if err := bls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BenefitLedgerQuery, *BenefitLedgerSelect](ctx, bls.BenefitLedgerQuery, bls, bls.inters, v)
}

func (bls *BenefitLedgerSelect) sqlScan(ctx context.Context, root *BenefitLedgerQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bls.fns))
	for _, fn := range bls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
