// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/benefitledger"
	"github.com/flexprice/flexprice/ent/predicate"
)

// BenefitLedgerDelete is the builder for deleting a BenefitLedger entity.
type BenefitLedgerDelete struct {
	config
	hooks    []Hook
	mutation *BenefitLedgerMutation
}

// Where appends a list predicates to the BenefitLedgerDelete builder.
func (bld *BenefitLedgerDelete) Where(ps ...predicate.BenefitLedger) *BenefitLedgerDelete {
	bld.mutation.Where(ps...)
	return bld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bld *BenefitLedgerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, bld.sqlExec, bld.mutation, bld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (bld *BenefitLedgerDelete) ExecX(ctx context.Context) int {
	n, err := bld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bld *BenefitLedgerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(benefitledger.Table, sqlgraph.NewFieldSpec(benefitledger.FieldID, field.TypeString))
	if ps := bld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, bld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	bld.mutation.done = true
	return affected, err
}

// BenefitLedgerDeleteOne is the builder for deleting a single BenefitLedger entity.
type BenefitLedgerDeleteOne struct {
	bld *BenefitLedgerDelete
}

// Where appends a list predicates to the BenefitLedgerDelete builder.
func (bldo *BenefitLedgerDeleteOne) Where(ps ...predicate.BenefitLedger) *BenefitLedgerDeleteOne {
	bldo.bld.mutation.Where(ps...)
	return bldo
}

// Exec executes the deletion query.
func (bldo *BenefitLedgerDeleteOne) Exec(ctx context.Context) error {
	n, err := bldo.bld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{benefitledger.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (bldo *BenefitLedgerDeleteOne) ExecX(ctx context.Context) {
	if err := bldo.Exec(ctx); err != nil {
		panic(err)
	}
}
