// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/benefitledger"
	"github.com/flexprice/flexprice/ent/predicate"
)

// BenefitLedgerUpdate is the builder for updating BenefitLedger entities.
type BenefitLedgerUpdate struct {
	config
	hooks    []Hook
	mutation *BenefitLedgerMutation
}

// Where appends a list predicates to the BenefitLedgerUpdate builder.
func (blu *BenefitLedgerUpdate) Where(ps ...predicate.BenefitLedger) *BenefitLedgerUpdate {
	blu.mutation.Where(ps...)
	return blu
}

// SetStatus sets the "status" field.
func (blu *BenefitLedgerUpdate) SetStatus(s string) *BenefitLedgerUpdate {
	blu.mutation.SetStatus(s)
	return blu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (blu *BenefitLedgerUpdate) SetNillableStatus(s *string) *BenefitLedgerUpdate {
	if s != nil {
		blu.SetStatus(*s)
	}
	return blu
}

// SetUpdatedAt sets the "updated_at" field.
func (blu *BenefitLedgerUpdate) SetUpdatedAt(t time.Time) *BenefitLedgerUpdate {
	blu.mutation.SetUpdatedAt(t)
	return blu
}

// SetUpdatedBy sets the "updated_by" field.
func (blu *BenefitLedgerUpdate) SetUpdatedBy(s string) *BenefitLedgerUpdate {
	blu.mutation.SetUpdatedBy(s)
	return blu
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (blu *BenefitLedgerUpdate) SetNillableUpdatedBy(s *string) *BenefitLedgerUpdate {
	if s != nil {
		blu.SetUpdatedBy(*s)
	}
	return blu
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (blu *BenefitLedgerUpdate) ClearUpdatedBy() *BenefitLedgerUpdate {
	blu.mutation.ClearUpdatedBy()
	return blu
}

// Mutation returns the BenefitLedgerMutation object of the builder.
func (blu *BenefitLedgerUpdate) Mutation() *BenefitLedgerMutation {
	return blu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (blu *BenefitLedgerUpdate) Save(ctx context.Context) (int, error) {
	blu.defaults()
	return withHooks(ctx, blu.sqlSave, blu.mutation, blu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (blu *BenefitLedgerUpdate) SaveX(ctx context.Context) int {
	affected, err := blu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (blu *BenefitLedgerUpdate) Exec(ctx context.Context) error {
	_, err := blu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (blu *BenefitLedgerUpdate) ExecX(ctx context.Context) {
	if err := blu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (blu *BenefitLedgerUpdate) defaults() {
	if _, ok := blu.mutation.UpdatedAt(); !ok {
		v := benefitledger.UpdateDefaultUpdatedAt()
		blu.mutation.SetUpdatedAt(v)
	}
}

func (blu *BenefitLedgerUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(benefitledger.Table, benefitledger.Columns, sqlgraph.NewFieldSpec(benefitledger.FieldID, field.TypeString))
	if ps := blu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := blu.mutation.Status(); ok {
		_spec.SetField(benefitledger.FieldStatus, field.TypeString, value)
	}
	if value, ok := blu.mutation.UpdatedAt(); ok {
		_spec.SetField(benefitledger.FieldUpdatedAt, field.TypeTime, value)
	}
	if blu.mutation.CreatedByCleared() {
		_spec.ClearField(benefitledger.FieldCreatedBy, field.TypeString)
	}
	if value, ok := blu.mutation.UpdatedBy(); ok {
		_spec.SetField(benefitledger.FieldUpdatedBy, field.TypeString, value)
	}
	if blu.mutation.UpdatedByCleared() {
		_spec.ClearField(benefitledger.FieldUpdatedBy, field.TypeString)
	}
	if blu.mutation.EnvironmentIDCleared() {
		_spec.ClearField(benefitledger.FieldEnvironmentID, field.TypeString)
	}
	if blu.mutation.FeatureIDCleared() {
		_spec.ClearField(benefitledger.FieldFeatureID, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, blu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{benefitledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	blu.mutation.done = true
	return n, nil
}

// BenefitLedgerUpdateOne is the builder for updating a single BenefitLedger entity.
type BenefitLedgerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BenefitLedgerMutation
}

// SetStatus sets the "status" field.
func (bluo *BenefitLedgerUpdateOne) SetStatus(s string) *BenefitLedgerUpdateOne {
	bluo.mutation.SetStatus(s)
	return bluo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (bluo *BenefitLedgerUpdateOne) SetNillableStatus(s *string) *BenefitLedgerUpdateOne {
	if s != nil {
		bluo.SetStatus(*s)
	}
	return bluo
}

// SetUpdatedAt sets the "updated_at" field.
func (bluo *BenefitLedgerUpdateOne) SetUpdatedAt(t time.Time) *BenefitLedgerUpdateOne {
	bluo.mutation.SetUpdatedAt(t)
	return bluo
}

// SetUpdatedBy sets the "updated_by" field.
func (bluo *BenefitLedgerUpdateOne) SetUpdatedBy(s string) *BenefitLedgerUpdateOne {
	bluo.mutation.SetUpdatedBy(s)
	return bluo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (bluo *BenefitLedgerUpdateOne) SetNillableUpdatedBy(s *string) *BenefitLedgerUpdateOne {
	if s != nil {
		bluo.SetUpdatedBy(*s)
	}
	return bluo
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (bluo *BenefitLedgerUpdateOne) ClearUpdatedBy() *BenefitLedgerUpdateOne {
	bluo.mutation.ClearUpdatedBy()
	return bluo
}

// Mutation returns the BenefitLedgerMutation object of the builder.
func (bluo *BenefitLedgerUpdateOne) Mutation() *BenefitLedgerMutation {
	return bluo.mutation
}

// Where appends a list predicates to the BenefitLedgerUpdate builder.
func (bluo *BenefitLedgerUpdateOne) Where(ps ...predicate.BenefitLedger) *BenefitLedgerUpdateOne {
	bluo.mutation.Where(ps...)
	return bluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (bluo *BenefitLedgerUpdateOne) Select(field string, fields ...string) *BenefitLedgerUpdateOne {
	bluo.fields = append([]string{field}, fields...)
	return bluo
}

// Save executes the query and returns the updated BenefitLedger entity.
func (bluo *BenefitLedgerUpdateOne) Save(ctx context.Context) (*BenefitLedger, error) {
	bluo.defaults()
	return withHooks(ctx, bluo.sqlSave, bluo.mutation, bluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bluo *BenefitLedgerUpdateOne) SaveX(ctx context.Context) *BenefitLedger {
	node, err := bluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (bluo *BenefitLedgerUpdateOne) Exec(ctx context.Context) error {
	_, err := bluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bluo *BenefitLedgerUpdateOne) ExecX(ctx context.Context) {
	if err := bluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bluo *BenefitLedgerUpdateOne) defaults() {
	if _, ok := bluo.mutation.UpdatedAt(); !ok {
		v := benefitledger.UpdateDefaultUpdatedAt()
		bluo.mutation.SetUpdatedAt(v)
	}
}

func (bluo *BenefitLedgerUpdateOne) sqlSave(ctx context.Context) (_node *BenefitLedger, err error) {
	_spec := sqlgraph.NewUpdateSpec(benefitledger.Table, benefitledger.Columns, sqlgraph.NewFieldSpec(benefitledger.FieldID, field.TypeString))
	id, ok := bluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BenefitLedger.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := bluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, benefitledger.FieldID)
		for _, f := range fields {
			if !benefitledger.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != benefitledger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := bluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bluo.mutation.Status(); ok {
		_spec.SetField(benefitledger.FieldStatus, field.TypeString, value)
	}
	if value, ok := bluo.mutation.UpdatedAt(); ok {
		_spec.SetField(benefitledger.FieldUpdatedAt, field.TypeTime, value)
	}
	if bluo.mutation.CreatedByCleared() {
		_spec.ClearField(benefitledger.FieldCreatedBy, field.TypeString)
	}
	if value, ok := bluo.mutation.UpdatedBy(); ok {
		_spec.SetField(benefitledger.FieldUpdatedBy, field.TypeString, value)
	}
	if bluo.mutation.UpdatedByCleared() {
		_spec.ClearField(benefitledger.FieldUpdatedBy, field.TypeString)
	}
	if bluo.mutation.EnvironmentIDCleared() {
		_spec.ClearField(benefitledger.FieldEnvironmentID, field.TypeString)
	}
	if bluo.mutation.FeatureIDCleared() {
		_spec.ClearField(benefitledger.FieldFeatureID, field.TypeString)
	}
	_node = &BenefitLedger{config: bluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, bluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{benefitledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	bluo.mutation.done = true
	return _node, nil
}
